import { defineCommand } from "citty";

import { startDevMcpServer } from "./dev-mcp.js";

/**
 * Deprecated alias for `dev-mcp`, kept because it is what every `.mcp.json`
 * already generated by `create-pracht` invokes. The notice goes to stderr for
 * the same reason everything else does: stdout is the MCP transport.
 */
export default defineCommand({
  meta: {
    name: "mcp",
    description: "Deprecated alias for `pracht dev-mcp`",
  },
  async run() {
    process.stderr.write(
      "pracht mcp is deprecated; use `pracht dev-mcp`. " +
        "(Your app's own remote MCP endpoint is a separate feature — see /docs/remote-mcp.)\n",
    );
    await startDevMcpServer();
  },
});
