import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, isAbsolute, relative, resolve } from "node:path";

import { defineCommand } from "citty";

import { displayPath } from "../project.js";
import { ensureTrailingNewline, handleCliError } from "../utils.js";
import { runInspect, type InspectReport } from "./inspect.js";

const DEFAULT_DECLARATION_OUT = "src/pracht-routes.d.ts";
const DEFAULT_RUNTIME_OUT = "src/pracht-routes.ts";

type RouteEntry = NonNullable<InspectReport["routes"]>[number];

export default defineCommand({
  meta: {
    name: "typegen",
    description: "Generate typed route declarations and href helpers",
  },
  args: {
    out: {
      type: "string",
      description: `Declaration output path (default: ${DEFAULT_DECLARATION_OUT})`,
    },
    "runtime-out": {
      type: "string",
      description: `Runtime href helper output path (default: ${DEFAULT_RUNTIME_OUT})`,
    },
    check: {
      type: "boolean",
      description: "Check whether generated route files are up to date without writing",
    },
    json: {
      type: "boolean",
      description: "Output as JSON",
    },
  },
  async run({ args }) {
    const json = Boolean(args.json);
    try {
      const result = await runTypegen({
        check: Boolean(args.check),
        declarationOut: typeof args.out === "string" ? args.out : DEFAULT_DECLARATION_OUT,
        root: process.cwd(),
        runtimeOut:
          typeof args["runtime-out"] === "string" ? args["runtime-out"] : DEFAULT_RUNTIME_OUT,
      });

      if (json) {
        console.log(JSON.stringify({ ok: true, ...result }, null, 2));
        return;
      }

      if (result.check) {
        console.log("Generated route files are up to date.");
        return;
      }

      console.log("Generated typed routes:");
      for (const file of result.files) {
        console.log(`  ${file}`);
      }
    } catch (error) {
      handleCliError(error, { json });
    }
  },
});

interface TypegenOptions {
  check: boolean;
  declarationOut: string;
  root: string;
  runtimeOut: string;
}

interface TypegenResult {
  check: boolean;
  files: string[];
  mode: string;
  routes: number;
}

async function runTypegen(options: TypegenOptions): Promise<TypegenResult> {
  const report = await runInspect(options.root, { target: "routes" });
  const routes = report.routes ?? [];
  validateRoutes(routes);

  const declarationPath = resolveOutputPath(options.root, options.declarationOut);
  const runtimePath = resolveOutputPath(options.root, options.runtimeOut);
  const outputs = [
    {
      path: declarationPath,
      source: buildDeclarationSource(routes),
    },
    {
      path: runtimePath,
      source: buildRuntimeSource(routes),
    },
  ];

  if (options.check) {
    const stale = outputs.filter((output) => !fileMatches(output.path, output.source));
    if (stale.length > 0) {
      const files = stale.map((output) => displayPath(options.root, output.path)).join(", ");
      throw new Error(`Generated route files are out of date: ${files}. Run \`pracht typegen\`.`);
    }
  } else {
    for (const output of outputs) {
      mkdirSync(dirname(output.path), { recursive: true });
      writeFileSync(output.path, output.source, "utf-8");
    }
  }

  return {
    check: options.check,
    files: outputs.map((output) => displayPath(options.root, output.path)),
    mode: report.mode,
    routes: routes.length,
  };
}

function validateRoutes(routes: RouteEntry[]): void {
  const seen = new Map<string, string>();
  for (const route of routes) {
    if (!route.id) {
      throw new Error(`Route ${route.path} resolved without an id.`);
    }

    const previousPath = seen.get(route.id);
    if (previousPath) {
      throw new Error(
        `Duplicate route id "${route.id}" for ${previousPath} and ${route.path}. Add explicit unique ids.`,
      );
    }
    seen.set(route.id, route.path);

    inferRouteParams(route.path);
  }
}

function buildDeclarationSource(routes: RouteEntry[]): string {
  const lines = [
    "// Generated by `pracht typegen`. Do not edit manually.",
    'import "@pracht/core";',
    'import type { RouteParamInput, SearchParamsInput } from "@pracht/core";',
    "",
    'declare module "@pracht/core" {',
    "  interface Register {",
    "    routes: {",
  ];

  for (const route of routes) {
    lines.push(`      ${JSON.stringify(route.id)}: {`);
    lines.push(`        path: ${JSON.stringify(route.path)};`);
    lines.push(`        params: ${formatParamsType(inferRouteParams(route.path))};`);
    lines.push(`        search: ${formatSearchType(route)};`);
    lines.push("      };");
  }

  lines.push("    };");
  lines.push("  }");
  lines.push("}");
  lines.push("");
  lines.push("export {};");
  lines.push("");

  return lines.join("\n");
}

function buildRuntimeSource(routes: RouteEntry[]): string {
  const lines = [
    "// Generated by `pracht typegen`. Do not edit manually.",
    'import { createHref } from "@pracht/core";',
    'import type { HrefRouteDefinition } from "@pracht/core";',
    "",
    "export const routes = [",
  ];

  for (const route of routes) {
    lines.push("  {");
    lines.push(`    id: ${JSON.stringify(route.id)},`);
    lines.push(`    path: ${JSON.stringify(route.path)},`);
    lines.push("  },");
  }

  lines.push("] as const satisfies readonly HrefRouteDefinition[];");
  lines.push("");
  lines.push("export const href = createHref(routes);");
  lines.push("");

  return lines.join("\n");
}

function inferRouteParams(path: string): string[] {
  const params: string[] = [];
  const seen = new Set<string>();

  for (const segment of path.split("/").filter(Boolean)) {
    let name: string | null = null;
    if (segment === "*") {
      name = "*";
    } else if (segment.startsWith(":")) {
      name = segment.endsWith("*") ? segment.slice(1, -1) || "*" : segment.slice(1);
    }

    if (!name) continue;
    if (seen.has(name)) {
      throw new Error(`Route ${path} declares duplicate param "${name}".`);
    }
    seen.add(name);
    params.push(name);
  }

  return params;
}

function formatParamsType(params: string[]): string {
  if (params.length === 0) {
    return "Record<never, never>";
  }

  const properties = params.map((param) => `${JSON.stringify(param)}: RouteParamInput;`).join(" ");
  return `{ ${properties} }`;
}

interface SearchParamInfo {
  array: boolean;
  kind: "string" | "number" | "boolean";
  optional: boolean;
}

function formatSearchType(route: RouteEntry): string {
  if (route.search == null) {
    return "SearchParamsInput";
  }

  if (!isPlainObject(route.search)) {
    throw new Error(`Route ${route.path} search schema must be an object.`);
  }

  const properties = Object.entries(route.search).map(([name, descriptor]) => {
    const param = parseSearchParamDescriptor(route.path, name, descriptor);
    const optional = param.optional ? "?" : "";
    const type = param.array ? `readonly ${param.kind}[]` : param.kind;
    return `${JSON.stringify(name)}${optional}: ${type};`;
  });

  if (properties.length === 0) {
    return "Record<never, never>";
  }

  return `{ ${properties.join(" ")} }`;
}

function parseSearchParamDescriptor(
  routePath: string,
  name: string,
  descriptor: unknown,
): SearchParamInfo {
  if (typeof descriptor === "string") {
    return parseSearchParamToken(routePath, name, descriptor, { array: false });
  }

  if (Array.isArray(descriptor)) {
    if (descriptor.length !== 1 || typeof descriptor[0] !== "string") {
      throw new Error(
        `Route ${routePath} search param "${name}" array schema must contain one type token.`,
      );
    }
    return parseSearchParamToken(routePath, name, descriptor[0], { array: true });
  }

  if (isPlainObject(descriptor)) {
    const type = descriptor.type;
    if (typeof type !== "string") {
      throw new Error(`Route ${routePath} search param "${name}" object schema needs a type.`);
    }
    const param = parseSearchParamToken(routePath, name, type, {
      array: descriptor.array === true,
    });
    return {
      ...param,
      optional: descriptor.optional === true,
    };
  }

  throw new Error(`Route ${routePath} search param "${name}" has an invalid schema.`);
}

function parseSearchParamToken(
  routePath: string,
  name: string,
  token: string,
  options: { array: boolean },
): SearchParamInfo {
  const optional = token.endsWith("?");
  const kind = optional ? token.slice(0, -1) : token;
  if (kind !== "string" && kind !== "number" && kind !== "boolean") {
    throw new Error(
      `Route ${routePath} search param "${name}" uses unsupported type "${token}". Use string, number, or boolean.`,
    );
  }
  return {
    array: options.array,
    kind,
    optional,
  };
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function resolveOutputPath(root: string, outputPath: string): string {
  const absolutePath = isAbsolute(outputPath) ? outputPath : resolve(root, outputPath);
  const relativePath = relative(root, absolutePath);
  if (relativePath === "" || (!relativePath.startsWith("..") && !isAbsolute(relativePath))) {
    return absolutePath;
  }
  throw new Error(`Refusing to write outside the project root: ${outputPath}.`);
}

function fileMatches(path: string, source: string): boolean {
  return existsSync(path) && readFileSync(path, "utf-8") === ensureTrailingNewline(source);
}
