import { useState } from "preact/hooks";
import { Form, invokeCapability, useIsHydrated, useRouteData, type LoaderArgs } from "@pracht/core";

// Direct server-side invocation: the loader calls the same capability the
// HTTP projection serves, through the same validation + middleware pipeline.
// Input and output types are inferred from the capability name — they come
// from src/pracht-capabilities.d.ts, generated by `pracht typegen`.
export async function loader({ request, context, signal }: LoaderArgs) {
  const result = await invokeCapability(
    "notes.search",
    { query: "note" },
    { request, context, signal },
  );

  return {
    notes: result.ok ? result.data.notes : [],
    error: result.ok ? null : result.error.message,
  };
}

export function Component() {
  const data = useRouteData<typeof loader>();
  const hydrated = useIsHydrated();
  const [status, setStatus] = useState<string | null>(null);

  return (
    <section>
      <h1>Notes</h1>
      <ul data-testid="notes-list">
        {data.notes.map((note) => (
          <li key={note.id}>
            <strong>{note.title}</strong> — {note.body}
          </li>
        ))}
      </ul>
      {/*
        The form posts to the exact endpoint agents call — one contract for
        both users. Fields are coerced onto the capability's input schema
        server-side, the note list revalidates automatically after a
        successful submission, and without JavaScript the endpoint accepts
        the form-encoded post and redirects back to this page.
      */}
      <Form
        data-testid="create-note-form"
        data-hydrated={hydrated}
        capability="notes.create"
        onCapabilityResult={(result) => {
          setStatus(
            result.ok ? `Created "${result.data.note.title}"` : `Error: ${result.error.message}`,
          );
        }}
      >
        <input name="title" placeholder="Note title" />
        <input type="hidden" name="body" value="Created from the browser." />
        <button type="submit">Create note</button>
      </Form>
      {status ? <p data-testid="create-note-status">{status}</p> : null}
    </section>
  );
}
