// Generated by `pracht typegen`. Do not edit manually.
import "@pracht/core";
import type { ApiRouteMethodMap, RouteLoaderData, RouteParamInput, RouteSearchInput, RouteSearchOutput } from "@pracht/core";

declare module "@pracht/core" {
  interface Register {
    routes: {
      "home": {
        path: "/";
        params: Record<never, never>;
        search: RouteSearchInput<typeof import("./routes/home")>;
        searchOutput: RouteSearchOutput<typeof import("./routes/home")>;
        data: RouteLoaderData<typeof import("./routes/home")>;
      };
      "notes": {
        path: "/notes";
        params: Record<never, never>;
        search: RouteSearchInput<typeof import("./routes/notes")>;
        searchOutput: RouteSearchOutput<typeof import("./routes/notes")>;
        data: RouteLoaderData<typeof import("./routes/notes")>;
      };
      "login": {
        path: "/login";
        params: Record<never, never>;
        search: RouteSearchInput<typeof import("./routes/login")>;
        searchOutput: RouteSearchOutput<typeof import("./routes/login")>;
        data: RouteLoaderData<typeof import("./routes/login")>;
      };
      "agent-tools": {
        path: "/agent-tools";
        params: Record<never, never>;
        search: RouteSearchInput<typeof import("./routes/agent-tools")>;
        searchOutput: RouteSearchOutput<typeof import("./routes/agent-tools")>;
        data: RouteLoaderData<typeof import("./routes/agent-tools")>;
      };
      "product": {
        path: "/products/:productId";
        params: { "productId": RouteParamInput; };
        search: RouteSearchInput<typeof import("./routes/product")>;
        searchOutput: RouteSearchOutput<typeof import("./routes/product")>;
        data: RouteLoaderData<typeof import("./routes/product")>;
      };
      "pricing": {
        path: "/pricing";
        params: Record<never, never>;
        search: RouteSearchInput<typeof import("./routes/pricing")>;
        searchOutput: RouteSearchOutput<typeof import("./routes/pricing")>;
        data: RouteLoaderData<typeof import("./routes/pricing")>;
      };
      "catalog": {
        path: "/catalog";
        params: Record<never, never>;
        search: RouteSearchInput<typeof import("./routes/catalog")>;
        searchOutput: RouteSearchOutput<typeof import("./routes/catalog")>;
        data: RouteLoaderData<typeof import("./routes/catalog")>;
      };
      "gallery": {
        path: "/gallery";
        params: Record<never, never>;
        search: RouteSearchInput<typeof import("./routes/gallery")>;
        searchOutput: RouteSearchOutput<typeof import("./routes/gallery")>;
        data: RouteLoaderData<typeof import("./routes/gallery")>;
      };
      "live": {
        path: "/live";
        params: Record<never, never>;
        search: RouteSearchInput<typeof import("./routes/live")>;
        searchOutput: RouteSearchOutput<typeof import("./routes/live")>;
        data: RouteLoaderData<typeof import("./routes/live")>;
      };
      "greeting": {
        path: "/greeting";
        params: Record<never, never>;
        search: RouteSearchInput<typeof import("./routes/greeting")>;
        searchOutput: RouteSearchOutput<typeof import("./routes/greeting")>;
        data: RouteLoaderData<typeof import("./routes/greeting")>;
      };
      "welcome": {
        path: "/welcome";
        params: Record<never, never>;
        search: RouteSearchInput<typeof import("./routes/welcome-redirect")>;
        searchOutput: RouteSearchOutput<typeof import("./routes/welcome-redirect")>;
        data: RouteLoaderData<typeof import("./routes/welcome-redirect")>;
      };
      "welcome-en": {
        path: "/en/welcome";
        params: Record<never, never>;
        search: RouteSearchInput<typeof import("./routes/welcome")>;
        searchOutput: RouteSearchOutput<typeof import("./routes/welcome")>;
        data: RouteLoaderData<typeof import("./routes/welcome")>;
      };
      "welcome-nl": {
        path: "/nl/welcome";
        params: Record<never, never>;
        search: RouteSearchInput<typeof import("./routes/welcome")>;
        searchOutput: RouteSearchOutput<typeof import("./routes/welcome")>;
        data: RouteLoaderData<typeof import("./routes/welcome")>;
      };
      "dashboard": {
        path: "/dashboard";
        params: Record<never, never>;
        search: RouteSearchInput<typeof import("./routes/dashboard")>;
        searchOutput: RouteSearchOutput<typeof import("./routes/dashboard")>;
        data: RouteLoaderData<typeof import("./routes/dashboard")>;
      };
      "settings": {
        path: "/settings";
        params: Record<never, never>;
        search: RouteSearchInput<typeof import("./routes/settings")>;
        searchOutput: RouteSearchOutput<typeof import("./routes/settings")>;
        data: RouteLoaderData<typeof import("./routes/settings")>;
      };
    };
    apiRoutes: {
      "/api/_pracht/image": {
        path: "/api/_pracht/image";
        params: Record<never, never>;
        methods: ApiRouteMethodMap<typeof import("./api/_pracht/image")>;
      };
      "/api/auth/login": {
        path: "/api/auth/login";
        params: Record<never, never>;
        methods: ApiRouteMethodMap<typeof import("./api/auth/login")>;
      };
      "/api/auth/logout": {
        path: "/api/auth/logout";
        params: Record<never, never>;
        methods: ApiRouteMethodMap<typeof import("./api/auth/logout")>;
      };
      "/api/dashboard": {
        path: "/api/dashboard";
        params: Record<never, never>;
        methods: ApiRouteMethodMap<typeof import("./api/dashboard")>;
      };
      "/api/echo": {
        path: "/api/echo";
        params: Record<never, never>;
        methods: ApiRouteMethodMap<typeof import("./api/echo")>;
      };
      "/api/health": {
        path: "/api/health";
        params: Record<never, never>;
        methods: ApiRouteMethodMap<typeof import("./api/health")>;
      };
      "/api/live": {
        path: "/api/live";
        params: Record<never, never>;
        methods: ApiRouteMethodMap<typeof import("./api/live")>;
      };
      "/api/locale": {
        path: "/api/locale";
        params: Record<never, never>;
        methods: ApiRouteMethodMap<typeof import("./api/locale")>;
      };
    };
  }
}

export {};
