// Generated by `pracht typegen`. Do not edit manually.
import "@pracht/core";
import type { ApiRouteMethodMap, RouteLoaderData, RouteParamInput, SearchParamsInput } from "@pracht/core";

declare module "@pracht/core" {
  interface Register {
    routes: {
      "home": {
        path: "/";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/home")>;
      };
      "notes": {
        path: "/notes";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/notes")>;
      };
      "agent-tools": {
        path: "/agent-tools";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/agent-tools")>;
      };
      "product": {
        path: "/products/:productId";
        params: { "productId": RouteParamInput; };
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/product")>;
      };
      "pricing": {
        path: "/pricing";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/pricing")>;
      };
      "gallery": {
        path: "/gallery";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/gallery")>;
      };
      "dashboard": {
        path: "/dashboard";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/dashboard")>;
      };
      "settings": {
        path: "/settings";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/settings")>;
      };
    };
    apiRoutes: {
      "/api/_pracht/image": {
        path: "/api/_pracht/image";
        params: Record<never, never>;
        methods: ApiRouteMethodMap<typeof import("./api/_pracht/image")>;
      };
      "/api/dashboard": {
        path: "/api/dashboard";
        params: Record<never, never>;
        methods: ApiRouteMethodMap<typeof import("./api/dashboard")>;
      };
      "/api/echo": {
        path: "/api/echo";
        params: Record<never, never>;
        methods: ApiRouteMethodMap<typeof import("./api/echo")>;
      };
      "/api/health": {
        path: "/api/health";
        params: Record<never, never>;
        methods: ApiRouteMethodMap<typeof import("./api/health")>;
      };
    };
  }
}

export {};
