// Generated by `pracht typegen`. Do not edit manually.
import { createHref } from "@pracht/core";
import type { HrefRouteDefinition } from "@pracht/core";

export const routes = [
  {
    id: "home",
    path: "/",
  },
  {
    id: "notes",
    path: "/notes",
  },
  {
    id: "agent-tools",
    path: "/agent-tools",
  },
  {
    id: "product",
    path: "/products/:productId",
  },
  {
    id: "pricing",
    path: "/pricing",
  },
  {
    id: "gallery",
    path: "/gallery",
  },
  {
    id: "live",
    path: "/live",
  },
  {
    id: "greeting",
    path: "/greeting",
  },
  {
    id: "welcome",
    path: "/welcome",
  },
  {
    id: "welcome-en",
    path: "/en/welcome",
  },
  {
    id: "welcome-nl",
    path: "/nl/welcome",
  },
  {
    id: "dashboard",
    path: "/dashboard",
  },
  {
    id: "settings",
    path: "/settings",
  },
] as const satisfies readonly HrefRouteDefinition[];

export const href = createHref(routes);
