// Generated by `pracht typegen`. Do not edit manually.
import "@pracht/core";
import type { CapabilityClientMethod } from "@pracht/core";

declare module "@pracht/core" {
  interface Register {
    capabilities: {
      /**
       * Search projects
       *
       * Find Launchpad projects by name or summary. Returns id, name, status, environment and deploy count.
       */
      "projects.search": {
        input: { "query"?: string; "status"?: "any" | "live" | "building" | "paused" | "archived"; "limit"?: number; };
        output: { "projects": Array<{ "id": string; "name": string; "status": string; "environment": string; "deploys": number; "lastDeploy": string; "summary": string; [key: string]: unknown; }>; "count": number; [key: string]: unknown; };
        effect: "read";
        exposed: { http: true; webmcp: true; mcp: true };
      };
      /**
       * Create project
       *
       * Create a new Launchpad project. The project starts in the 'building' status.
       */
      "projects.create": {
        input: { "name": string; "summary"?: string; "environment"?: "production" | "preview"; };
        output: { "project": { "id": string; "name": string; "status": string; "environment": string; "deploys": number; "lastDeploy": string; "summary": string; [key: string]: unknown; }; [key: string]: unknown; };
        effect: "write";
        exposed: { http: true; webmcp: true; mcp: true };
      };
      /**
       * Deploy project
       *
       * Ship the current build of a project. Pass a stable idempotencyKey to make retries safe.
       */
      "projects.deploy": {
        input: { "projectId": string; "idempotencyKey"?: string; };
        output: { "deployed": boolean; "deduped": boolean; "deploys": number; "status": string; [key: string]: unknown; };
        effect: "write";
        exposed: { http: true; webmcp: true; mcp: true };
      };
      /**
       * Archive project
       *
       * Permanently archive a project. Requires a human approval before it runs — the caller receives a confirmation token, then waits for a reviewer.
       */
      "projects.archive": {
        input: { "projectId": string; "reason"?: string; };
        output: { "archived": boolean; "projectId": string; "name"?: string; [key: string]: unknown; };
        effect: "destructive";
        exposed: { http: true; webmcp: false; mcp: false };
      };
      /**
       * Who am I
       *
       * Report the verified Web Bot Auth (RFC 9421) identity Launchpad established for this request.
       */
      "agent.whoami": {
        input: Record<string, never>;
        output: { "verified": boolean; "agentDomain"?: string; "keyId"?: string; "policy": string; [key: string]: unknown; };
        effect: "read";
        exposed: { http: true; webmcp: true; mcp: true };
      };
      /**
       * Agent operating brief
       *
       * House rules for autonomous callers: which tools exist, which are gated, and how the archive approval flow works. Verified agents only.
       */
      "agent.brief": {
        input: Record<string, never>;
        output: { "agentDomain"?: string; "tools": Array<string>; "rules": Array<string>; [key: string]: unknown; };
        effect: "read";
        exposed: { http: true; webmcp: false; mcp: true };
      };
    };
    capabilityClient: {
      "projects": {
        /**
         * Search projects
         *
         * Find Launchpad projects by name or summary. Returns id, name, status, environment and deploy count.
         */
        "search": CapabilityClientMethod<"projects.search">;
        /**
         * Create project
         *
         * Create a new Launchpad project. The project starts in the 'building' status.
         */
        "create": CapabilityClientMethod<"projects.create">;
        /**
         * Deploy project
         *
         * Ship the current build of a project. Pass a stable idempotencyKey to make retries safe.
         */
        "deploy": CapabilityClientMethod<"projects.deploy">;
        /**
         * Archive project
         *
         * Permanently archive a project. Requires a human approval before it runs — the caller receives a confirmation token, then waits for a reviewer.
         */
        "archive": CapabilityClientMethod<"projects.archive">;
      };
      "agent": {
        /**
         * Who am I
         *
         * Report the verified Web Bot Auth (RFC 9421) identity Launchpad established for this request.
         */
        "whoami": CapabilityClientMethod<"agent.whoami">;
        /**
         * Agent operating brief
         *
         * House rules for autonomous callers: which tools exist, which are gated, and how the archive approval flow works. Verified agents only.
         */
        "brief": CapabilityClientMethod<"agent.brief">;
      };
    };
  }
}

export {};
