// Generated by `pracht typegen`. Do not edit manually.
import "@pracht/core";
import type { ApiRouteMethodMap, RouteLoaderData, RouteParamInput, SearchParamsInput } from "@pracht/core";

declare module "@pracht/core" {
  interface Register {
    routes: {
      "home": {
        path: "/";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/home")>;
      };
      "agents": {
        path: "/agents";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/agents")>;
      };
      "playground": {
        path: "/playground";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/playground")>;
      };
      "blog-post": {
        path: "/blog/:slug";
        params: { "slug": RouteParamInput; };
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/blog-post")>;
      };
      "pricing": {
        path: "/pricing";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/pricing")>;
      };
      "dashboard": {
        path: "/app";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/dashboard")>;
      };
      "project": {
        path: "/app/projects/:projectId";
        params: { "projectId": RouteParamInput; };
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/project")>;
      };
      "approvals": {
        path: "/app/approvals";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/approvals")>;
      };
      "audit": {
        path: "/app/audit";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/audit")>;
      };
      "settings": {
        path: "/app/settings";
        params: Record<never, never>;
        search: SearchParamsInput;
        data: RouteLoaderData<typeof import("./routes/settings")>;
      };
    };
    apiRoutes: {
      "/api/admin/approvals": {
        path: "/api/admin/approvals";
        params: Record<never, never>;
        methods: ApiRouteMethodMap<typeof import("./api/admin/approvals")>;
      };
      "/api/auth/login": {
        path: "/api/auth/login";
        params: Record<never, never>;
        methods: ApiRouteMethodMap<typeof import("./api/auth/login")>;
      };
      "/api/auth/logout": {
        path: "/api/auth/logout";
        params: Record<never, never>;
        methods: ApiRouteMethodMap<typeof import("./api/auth/logout")>;
      };
      "/api/demo/reset": {
        path: "/api/demo/reset";
        params: Record<never, never>;
        methods: ApiRouteMethodMap<typeof import("./api/demo/reset")>;
      };
      "/api/health": {
        path: "/api/health";
        params: Record<never, never>;
        methods: ApiRouteMethodMap<typeof import("./api/health")>;
      };
    };
  }
}

export {};
