// Generated by `pracht typegen`. Do not edit manually.
import { createHref } from "@pracht/core";
import type { HrefRouteDefinition } from "@pracht/core";

export const routes = [
  {
    id: "home",
    path: "/",
  },
  {
    id: "agents",
    path: "/agents",
  },
  {
    id: "playground",
    path: "/playground",
  },
  {
    id: "blog-post",
    path: "/blog/:slug",
  },
  {
    id: "pricing",
    path: "/pricing",
  },
  {
    id: "dashboard",
    path: "/app",
  },
  {
    id: "project",
    path: "/app/projects/:projectId",
  },
  {
    id: "approvals",
    path: "/app/approvals",
  },
  {
    id: "audit",
    path: "/app/audit",
  },
  {
    id: "settings",
    path: "/app/settings",
  },
] as const satisfies readonly HrefRouteDefinition[];

export const href = createHref(routes);
