// Generated by `pracht typegen`. Do not edit manually.
import { createHref } from "@pracht/core";
import type { HrefRouteDefinition } from "@pracht/core";

export const routes = [
  {
    id: "home",
    path: "/",
  },
  {
    id: "pricing",
    path: "/pricing",
  },
  {
    id: "product",
    path: "/products/:id",
  },
  {
    id: "slow",
    path: "/slow",
  },
  {
    id: "long",
    path: "/long",
  },
  {
    id: "dashboard",
    path: "/dashboard",
  },
  {
    id: "settings",
    path: "/settings",
  },
] as const satisfies readonly HrefRouteDefinition[];

export const href = createHref(routes);
