import type { ResolvedPrachtOpenApiOptions } from "./model.ts";

const PRACHT_SERVER_MODULE_ID = "virtual:pracht/server";
export const PRACHT_DEV_MODULE_ID = "virtual:pracht/dev-metadata";

export function isPrachtGraphModule(id: string): boolean {
  const normalized = (id.charCodeAt(0) === 0 ? id.slice(1) : id).split("?")[0];
  return normalized === PRACHT_SERVER_MODULE_ID || normalized === PRACHT_DEV_MODULE_ID;
}

export function createOpenApiServerModuleSource(options: ResolvedPrachtOpenApiOptions): string {
  const serializable = {
    documentPath: options.documentPath,
    document: options.document,
    failOnWarnings: options.failOnWarnings,
    info: options.info,
    ui: options.ui,
  };
  return [
    '// Generated by the opt-in "@pracht/openapi/vite" companion plugin.',
    'import { createOpenApiUiHtml as __prachtCreateOpenApiUiHtml, generateOpenApiDocument as __prachtGenerateOpenApiDocument } from "@pracht/openapi";',
    `const __prachtOpenApiConfig = ${JSON.stringify(serializable)};`,
    "async function __prachtLoadOpenApiRoute(file) {",
    "  const load = apiModules[file];",
    '  if (typeof load !== "function") {',
    "    throw new Error(`No API module importer exists for ${JSON.stringify(file)}.`);",
    "  }",
    "  return load();",
    "}",
    "export async function generatePrachtOpenApiArtifacts() {",
    "  const result = await __prachtGenerateOpenApiDocument({",
    "    info: __prachtOpenApiConfig.info,",
    "    document: __prachtOpenApiConfig.document,",
    "    routes: apiRoutes,",
    "    loadModule: __prachtLoadOpenApiRoute,",
    "  });",
    "  if (__prachtOpenApiConfig.failOnWarnings && result.warnings.length > 0) {",
    '    const summary = result.warnings.map((warning) => `${warning.method ? warning.method + " " : ""}${warning.path}: ${warning.message}`).join("\\n");',
    "    throw new Error(`OpenAPI generation produced ${result.warnings.length} warning(s):\\n${summary}`);",
    "  }",
    "  const artifacts = [{",
    "    path: __prachtOpenApiConfig.documentPath,",
    "    outputPath: __prachtOpenApiConfig.documentPath.slice(1),",
    '    contentType: "application/json; charset=utf-8",',
    '    content: JSON.stringify(result.document, null, 2) + "\\n",',
    "  }];",
    "  if (__prachtOpenApiConfig.ui) {",
    "    artifacts.push({",
    "      path: __prachtOpenApiConfig.ui.path,",
    '      outputPath: __prachtOpenApiConfig.ui.path.slice(1) + "/index.html",',
    '      contentType: "text/html; charset=utf-8",',
    "      content: __prachtCreateOpenApiUiHtml({",
    "        ...__prachtOpenApiConfig.ui,",
    "        documentUrl: __prachtOpenApiConfig.documentPath,",
    '        title: __prachtOpenApiConfig.ui.title ?? __prachtOpenApiConfig.info.title + " API reference",',
    "      }),",
    "    });",
    "  }",
    "  return { artifacts, warnings: result.warnings };",
    "}",
    "",
  ].join("\n");
}
