import { describe, expect, it } from "vitest";

import { generatedSourceMatches } from "../src/generated-source.ts";

const GENERATED = `// Generated by \`pracht typegen\`. Do not edit manually.
import { createHref } from "@pracht/core";
import type { HrefRouteDefinition } from "@pracht/core";

export const routes = [
  {
    id: "home",
    path: "/",
  },
  {
    id: "post",
    path: "/posts/:slug",
  },
] as const satisfies readonly HrefRouteDefinition[];

export const href = createHref(routes);
`;

describe("generatedSourceMatches", () => {
  it("matches an identical file", () => {
    expect(generatedSourceMatches(GENERATED, GENERATED)).toBe(true);
  });

  it("matches after a formatter has been over the file", () => {
    // Single quotes, no semicolons, no trailing commas, four-space indent,
    // collapsed lines — every difference a formatter is free to introduce.
    const formatted = `// Generated by \`pracht typegen\`. Do not edit manually.
import { createHref } from '@pracht/core'
import type { HrefRouteDefinition } from '@pracht/core'

export const routes = [
    { id: 'home', path: '/' },
    { id: 'post', path: '/posts/:slug' }
] as const satisfies readonly HrefRouteDefinition[]

export const href = createHref(routes)
`;

    expect(generatedSourceMatches(formatted, GENERATED)).toBe(true);
  });

  it("reports a stale route path", () => {
    expect(generatedSourceMatches(GENERATED.replace("/posts/:slug", "/posts/:id"), GENERATED)).toBe(
      false,
    );
  });

  it("reports a stale route id, an added route, and a removed one", () => {
    expect(generatedSourceMatches(GENERATED.replace('"post"', '"article"'), GENERATED)).toBe(false);
    expect(
      generatedSourceMatches(
        GENERATED.replace("] as const", '  { id: "extra", path: "/extra" },\n] as const'),
        GENERATED,
      ),
    ).toBe(false);
    expect(
      generatedSourceMatches(
        GENERATED.replace('  {\n    id: "post",\n    path: "/posts/:slug",\n  },\n', ""),
        GENERATED,
      ),
    ).toBe(false);
  });

  it("compares the JSDoc a capability's title and description turn into", () => {
    const withDoc = `declare module "@pracht/core" {
  interface Register {
    capabilities: {
      /**
       * Search notes
       *
       * Find matching notes.
       */
      "notes.search": { effect: "read" };
    };
  }
}
`;
    // Re-indented the way a formatter would, same prose: still up to date.
    const reindented = withDoc.replace(/^ {6}/gm, "        ");
    expect(generatedSourceMatches(reindented, withDoc)).toBe(true);

    // Different prose: the contract changed and the file is stale.
    expect(
      generatedSourceMatches(withDoc.replace("Find matching", "Finds matching"), withDoc),
    ).toBe(false);
  });

  it("does not let a dropped declaration hide behind punctuation", () => {
    const withoutEffect = `export const routes = [{ id: "home" }] as const;\n`;
    const withEffect = `export const routes = [{ id: "home", effect: "read" }] as const;\n`;

    expect(generatedSourceMatches(withoutEffect, withEffect)).toBe(false);
  });

  it("treats an empty or truncated file as stale", () => {
    expect(generatedSourceMatches("", GENERATED)).toBe(false);
    expect(generatedSourceMatches(GENERATED.slice(0, 120), GENERATED)).toBe(false);
  });
});
