import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { extname, join, posix, relative } from "node:path";

export interface PagesRouterOptions {
  dir?: string;
  defaultRender?: "ssr" | "ssg" | "spa" | "isg";
  outFile?: string;
}

export interface ResolvedPagesRouterOptions {
  dir: string;
  defaultRender: "ssr" | "ssg" | "spa" | "isg";
  outFile: string;
}

interface PageEntry {
  /** Relative path from pages dir, e.g. "blog/[slug].tsx" */
  relativePath: string;
  /** Computed route path, e.g. "/blog/:slug" */
  routePath: string;
  /** Whether this is the _app shell file */
  isShell: boolean;
}

const PAGE_EXTENSIONS = new Set([".tsx", ".ts", ".jsx", ".js", ".md", ".mdx"]);
const RENDER_MODE_RE = /export\s+const\s+render\s*=\s*["'](ssr|ssg|spa|isg)["']/;

export function resolvePagesOptions(
  options: PagesRouterOptions | boolean,
): ResolvedPagesRouterOptions {
  const opts = typeof options === "boolean" ? {} : options;
  return {
    dir: opts.dir ?? "/src/pages",
    defaultRender: opts.defaultRender ?? "ssr",
    outFile: opts.outFile ?? "/src/routes.generated.ts",
  };
}

export function scanPagesDirectory(root: string, pagesDir: string): PageEntry[] {
  const absoluteDir = join(root, pagesDir);
  if (!existsSync(absoluteDir)) return [];

  const entries: PageEntry[] = [];
  const files = readdirSync(absoluteDir, { recursive: true, withFileTypes: true });

  for (const file of files) {
    if (!file.isFile()) continue;
    const ext = extname(file.name);
    if (!PAGE_EXTENSIONS.has(ext)) continue;

    // Build the relative path from the pages dir
    const parentPath = file.parentPath ?? (file as any).path ?? absoluteDir;
    const relativePath = posix.join(
      relative(absoluteDir, parentPath).split("\\").join("/"),
      file.name,
    );

    // Skip files in _ prefixed directories (except the file itself can be _app)
    const parts = relativePath.split("/");
    const dirParts = parts.slice(0, -1);
    if (dirParts.some((p) => p.startsWith("_"))) continue;

    const baseName = file.name.replace(ext, "");

    // _app at root level is the shell
    if (baseName === "_app" && dirParts.length === 0) {
      entries.push({ relativePath, routePath: "", isShell: true });
      continue;
    }

    // Skip other _ prefixed files
    if (baseName.startsWith("_")) continue;

    const routePath = filePathToRoutePath(relativePath);
    entries.push({ relativePath, routePath, isShell: false });
  }

  // Sort routes: static before dynamic, shorter before longer
  entries.sort((a, b) => {
    if (a.isShell !== b.isShell) return a.isShell ? -1 : 1;
    const aDynamic = a.routePath.includes(":") || a.routePath.includes("*");
    const bDynamic = b.routePath.includes(":") || b.routePath.includes("*");
    if (aDynamic !== bDynamic) return aDynamic ? 1 : -1;
    return a.routePath.localeCompare(b.routePath);
  });

  return entries;
}

export function filePathToRoutePath(relativePath: string): string {
  // Strip extension
  let route = relativePath.replace(/\.(tsx?|jsx?|mdx?)$/, "");

  // index files map to parent directory
  if (route.endsWith("/index")) {
    route = route.slice(0, -"/index".length) || "";
  } else if (route === "index") {
    route = "";
  }

  // Convert [...param] to * (catch-all)
  route = route.replace(/\[\.\.\.([^\]]+)\]/g, "*");

  // Convert [param] to :param
  route = route.replace(/\[([^\]]+)\]/g, ":$1");

  return "/" + route;
}

function routePathToId(routePath: string): string {
  if (routePath === "/") return "index";
  return routePath
    .slice(1) // remove leading /
    .replace(/[/:*]/g, "-") // replace special chars with dashes
    .replace(/-+/g, "-") // collapse multiple dashes
    .replace(/-$/, ""); // remove trailing dash
}

function detectRenderMode(root: string, pagesDir: string, relativePath: string): string | null {
  const filePath = join(root, pagesDir, relativePath);
  try {
    const content = readFileSync(filePath, "utf-8");
    const match = content.match(RENDER_MODE_RE);
    return match ? match[1] : null;
  } catch {
    return null;
  }
}

export function generateRoutesFileContent(
  root: string,
  entries: PageEntry[],
  options: ResolvedPagesRouterOptions,
): string {
  const shell = entries.find((e) => e.isShell);
  const routes = entries.filter((e) => !e.isShell);

  if (routes.length === 0 && !shell) {
    return [
      "// Auto-generated by viact pages router — do not edit manually.",
      "// To eject, remove the `pages` option from your viact plugin config",
      "// and rename this file to routes.ts.",
      "",
      'import { defineApp } from "viact";',
      "",
      "export const app = defineApp({",
      "  routes: [],",
      "});",
      "",
    ].join("\n");
  }

  const lines: string[] = [
    "// Auto-generated by viact pages router — do not edit manually.",
    "// To eject, remove the `pages` option from your viact plugin config",
    "// and rename this file to routes.ts.",
    "",
    'import { defineApp, route, group } from "viact";',
    "",
  ];

  const shellPath = shell ? `.${options.dir}/${shell.relativePath}` : null;

  lines.push("export const app = defineApp({");

  if (shellPath) {
    lines.push(`  shells: {`);
    lines.push(`    root: ${JSON.stringify(shellPath)},`);
    lines.push(`  },`);
  }

  lines.push("  routes: [");

  if (shellPath) {
    lines.push(`    group({ shell: "root" }, [`);
  }

  const indent = shellPath ? "      " : "    ";

  for (const entry of routes) {
    const filePath = `.${options.dir}/${entry.relativePath}`;
    const id = routePathToId(entry.routePath);
    const renderMode = detectRenderMode(root, options.dir, entry.relativePath);
    const render = renderMode ?? options.defaultRender;

    lines.push(
      `${indent}route(${JSON.stringify(entry.routePath)}, ${JSON.stringify(filePath)}, { id: ${JSON.stringify(id)}, render: ${JSON.stringify(render)} }),`,
    );
  }

  if (shellPath) {
    lines.push("    ]),");
  }

  lines.push("  ],");
  lines.push("});");
  lines.push("");

  return lines.join("\n");
}

export function generateAndWriteRoutes(root: string, options: ResolvedPagesRouterOptions): boolean {
  const entries = scanPagesDirectory(root, options.dir);
  const content = generateRoutesFileContent(root, entries, options);
  const outPath = join(root, options.outFile);

  // Diff-before-write to prevent infinite HMR loops
  if (existsSync(outPath)) {
    const existing = readFileSync(outPath, "utf-8");
    if (existing === content) return false;
  }

  writeFileSync(outPath, content, "utf-8");
  return true;
}
