/**
 * Dev-only WebMCP page tools: the generated `virtual:pracht/dev-page-tools`
 * module and the `<script>` tag that loads it into every dev document.
 *
 * The runtime — tool definitions, dispatch, feature detection of the WebMCP
 * API — lives in `@pracht/core/dev-page-tools`. This file only decides *when*
 * it loads: the dev SSR middleware transforms every HTML document through
 * Vite's `transformIndexHtml`, and the tag added there reaches full-hydration
 * routes, islands routes, `hydration: "none"` routes, the dev 404 page, and
 * the error overlay alike. No build step emits the tag or the module, so a
 * production bundle cannot contain either.
 */

import { existsSync, readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import type { HtmlTagDescriptor } from "vite";

import { DEV_PAGE_TOOLS_BROWSER_PATH } from "./plugin-assets.ts";
import { DEVTOOLS_JSON_PATH, DEVTOOLS_PATH } from "./plugin-dev-ssr.ts";

export function createPrachtDevPageToolsModuleSource(options: {
  root?: string;
  base?: string;
}): string {
  const base = options.base && options.base !== "/" ? options.base : "/";
  const devtoolsJsonUrl = `${base}${DEVTOOLS_JSON_PATH.slice(1)}`;
  const root = options.root ?? process.cwd();

  // The app's own `@pracht/core` must carry the entry. When it predates it
  // (plugin upgraded ahead of the runtime), a broken import would surface as
  // a red console error on every page in dev; one warning says what to do.
  if (!appCoreHasDevPageTools(root)) {
    return [
      "// Generated by @pracht/vite-plugin — dev-only WebMCP page tools (unavailable).",
      'console.warn("[pracht] The installed @pracht/core has no dev-page-tools entry; upgrade it to expose dev page tools to agents.");',
      "",
    ].join("\n");
  }

  return [
    "// Generated by @pracht/vite-plugin — dev-only WebMCP page tools.",
    "// Feature-detect before importing anything: a browser without the WebMCP",
    "// API pays for this file alone, never for the runtime behind it.",
    `const DEVTOOLS_JSON_URL = ${JSON.stringify(devtoolsJsonUrl)};`,
    "let registration = null;",
    'if (typeof document !== "undefined" && document.modelContext) {',
    '  import("@pracht/core/dev-page-tools")',
    "    .then((mod) => {",
    "      registration = mod.registerDevPageTools({ devtoolsJsonUrl: DEVTOOLS_JSON_URL });",
    "    })",
    "    .catch((error) => {",
    '      console.warn("[pracht] Dev page tools did not load:", error);',
    "    });",
    "}",
    "if (import.meta.hot) {",
    "  import.meta.hot.dispose(() => {",
    "    registration?.abort();",
    "  });",
    "}",
    "",
  ].join("\n");
}

/**
 * Whether the app's installed `@pracht/core` ships the dev-page-tools entry.
 * Also gates the dep-optimizer include for it, so a plugin upgraded ahead of
 * the runtime warns once instead of also failing dependency optimization.
 */
export function appCoreHasDevPageTools(root: string): boolean {
  // Walk up like Node's resolver would, reading the package manifest directly:
  // an older `@pracht/core` has an `exports` map without `./package.json`, so
  // `require.resolve("@pracht/core/package.json")` cannot tell "old" from
  // "absent".
  let dir = resolve(root);
  while (true) {
    const manifest = join(dir, "node_modules", "@pracht", "core", "package.json");
    if (existsSync(manifest)) {
      try {
        const pkg = JSON.parse(readFileSync(manifest, "utf-8")) as {
          exports?: Record<string, unknown>;
        };
        return pkg.exports?.["./dev-page-tools"] !== undefined;
      } catch {
        return false;
      }
    }
    const parent = dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  // No installed copy at all (a fixture without node_modules): let Vite
  // resolve the import exactly as it does for the client entry's own
  // `@pracht/core/client`.
  return true;
}

/**
 * Whether a dev document at `path` should load the dev page tools. `path` is
 * the base-free request path: Vite's base middleware strips the deploy base
 * from `req.url` before the dev SSR handler runs, and that is the URL the
 * middleware hands to `transformIndexHtml`.
 */
export function shouldInjectDevPageTools(path: string): boolean {
  const pathname = path.split("?")[0].split("#")[0];
  // The devtools page describes the whole app, not one route; nothing there
  // for a tab-scoped tool to report.
  return pathname !== DEVTOOLS_PATH && pathname !== DEVTOOLS_JSON_PATH;
}

/** The `<script type="module">` tag that loads the dev page tools module. */
export function createDevPageToolsScriptTag(base: string): HtmlTagDescriptor {
  const src =
    base && base !== "/"
      ? `${base}${DEV_PAGE_TOOLS_BROWSER_PATH.slice(1)}`
      : DEV_PAGE_TOOLS_BROWSER_PATH;
  return {
    tag: "script",
    attrs: { type: "module", src },
    injectTo: "head",
  };
}
