import { formatBytes } from "./bundle-report.js";
import { formatPlanMarkdown, GRAPH_SNAPSHOT_PATH } from "./graph-snapshot.js";
import { describeMissingBase, runPlan, type PlanReport } from "./plan.js";
import { runVerification, type VerificationReport } from "./verification.js";

export interface ReportOptions {
  base: string;
  baseExplicit?: boolean;
}

export async function runReport(root: string, options: ReportOptions): Promise<string> {
  const plan = await runPlan(root, { base: options.base, baseExplicit: options.baseExplicit });
  const verification = await runVerification(root);

  return [
    formatGraphSection(plan),
    formatVerificationSection(verification),
    formatBudgetSection(plan),
    "---",
    "_Generated by `pracht report` from the resolved app graph, `pracht verify`, and the last build's budget report — the sections above are machine-derived, not hand-written._",
  ]
    .filter(Boolean)
    .join("\n\n");
}

function formatGraphSection(plan: PlanReport): string {
  const budgets = new Map(Object.entries(plan.budgets));
  const lines = [formatPlanMarkdown(plan.diff, { base: plan.baseResolved, budgets })];

  if (plan.staleSnapshot) {
    lines.push(
      `> ⚠ ${GRAPH_SNAPSHOT_PATH} is stale — run \`pracht plan --write\` and commit the result.`,
    );
  }
  if (!plan.baseResolved) {
    lines.push(`> ℹ The diff above treats every entry as added: ${describeMissingBase(plan)}`);
  }

  return lines.join("\n\n");
}

function formatVerificationSection(report: VerificationReport): string {
  const errors = report.checks.filter((check) => check.status === "error");
  const warnings = report.checks.filter((check) => check.status === "warning");
  const okCount = report.checks.length - errors.length - warnings.length;

  const lines = [
    "### Verification",
    "",
    `\`pracht verify\` (${report.mode} mode): ${report.ok ? "✅ passing" : "❌ failing"} — ${okCount} ok, ${warnings.length} warning${warnings.length === 1 ? "" : "s"}, ${errors.length} error${errors.length === 1 ? "" : "s"}.`,
  ];

  for (const check of errors) {
    lines.push(`- ❌ ${check.message}`);
  }
  for (const check of warnings) {
    lines.push(`- ⚠ ${check.message}`);
  }

  return lines.join("\n");
}

function formatBudgetSection(plan: PlanReport): string | null {
  const entries = Object.entries(plan.budgets);
  if (entries.length === 0) return null;

  const lines = [
    "### Client JS budgets",
    "",
    "| Route | Gzip | Limit | Status |",
    "| --- | --- | --- | --- |",
  ];
  for (const [path, budget] of entries) {
    lines.push(
      `| \`${path}\` | ${formatBytes(budget.gzipBytes)} | ${formatBytes(budget.limitBytes)} | ${budget.ok ? "✅" : "❌ over"} |`,
    );
  }
  lines.push("", "_From the last `pracht build` budget report._");

  return lines.join("\n");
}
