/** Route/API declaration and runtime href-helper source generation. */

import { relative, resolve } from "node:path";

import type { InspectReport } from "./inspect.js";
import { resolveProjectPath } from "./project.js";

type RouteEntry = NonNullable<InspectReport["routes"]>[number];
type ApiRouteEntry = NonNullable<InspectReport["api"]>[number];

export interface DeclarationContext {
  appDir: string;
  declarationDir: string;
  root: string;
}

export function buildDeclarationSource(
  routes: RouteEntry[],
  apiRoutes: ApiRouteEntry[],
  context: DeclarationContext,
): string {
  const importsApiMethodMap = apiRoutes.some((route) => formatModuleSpecifier(route.file, context));
  const typeImports = [
    ...(importsApiMethodMap ? ["ApiRouteMethodMap"] : []),
    "RouteLoaderData",
    "RouteParamInput",
    "SearchParamsInput",
  ];
  const lines = [
    "// Generated by `pracht typegen`. Do not edit manually.",
    'import "@pracht/core";',
    `import type { ${typeImports.join(", ")} } from "@pracht/core";`,
    "",
    'declare module "@pracht/core" {',
    "  interface Register {",
    "    routes: {",
  ];

  for (const route of routes) {
    lines.push(`      ${JSON.stringify(route.id)}: {`);
    lines.push(`        path: ${JSON.stringify(route.path)};`);
    lines.push(`        params: ${formatParamsType(inferRouteParams(route.path))};`);
    lines.push("        search: SearchParamsInput;");
    lines.push(`        data: ${formatRouteDataType(route, context)};`);
    lines.push("      };");
  }

  lines.push("    };");
  lines.push("    apiRoutes: {");

  for (const route of apiRoutes) {
    const moduleSpecifier = formatModuleSpecifier(route.file, context);
    lines.push(`      ${JSON.stringify(route.path)}: {`);
    lines.push(`        path: ${JSON.stringify(route.path)};`);
    lines.push(`        params: ${formatParamsType(inferRouteParams(route.path))};`);
    lines.push(
      moduleSpecifier
        ? `        methods: ApiRouteMethodMap<typeof import(${moduleSpecifier})>;`
        : "        methods: Record<never, never>;",
    );
    lines.push("      };");
  }

  lines.push("    };");
  lines.push("  }");
  lines.push("}");
  lines.push("");
  lines.push("export {};");
  lines.push("");

  return lines.join("\n");
}

export function buildRuntimeSource(routes: RouteEntry[]): string {
  const lines = [
    "// Generated by `pracht typegen`. Do not edit manually.",
    'import { createHref } from "@pracht/core";',
    'import type { HrefRouteDefinition } from "@pracht/core";',
    "",
    "export const routes = [",
  ];

  for (const route of routes) {
    lines.push("  {");
    lines.push(`    id: ${JSON.stringify(route.id)},`);
    lines.push(`    path: ${JSON.stringify(route.path)},`);
    lines.push("  },");
  }

  lines.push("] as const satisfies readonly HrefRouteDefinition[];");
  lines.push("");
  lines.push("export const href = createHref(routes);");
  lines.push("");

  return lines.join("\n");
}

export function inferRouteParams(path: string): string[] {
  const params: string[] = [];
  const seen = new Set<string>();

  for (const segment of path.split("/").filter(Boolean)) {
    let name: string | null = null;
    if (segment === "*") {
      name = "*";
    } else if (segment.startsWith(":")) {
      name = segment.endsWith("*") ? segment.slice(1, -1) || "*" : segment.slice(1);
    }

    if (!name) continue;
    if (seen.has(name)) {
      throw new Error(`Route ${path} declares duplicate param "${name}".`);
    }
    seen.add(name);
    params.push(name);
  }

  return params;
}

// Only modules TypeScript can resolve type-only imports for. Route files in
// other formats (`.md`, `.mdx`, `.tsrx`) fall back to `unknown` data.
const IMPORTABLE_MODULE_PATTERN = /\.(ts|tsx|js|jsx)$/;

function formatRouteDataType(route: RouteEntry, context: DeclarationContext): string {
  const routeModule = formatModuleSpecifier(route.file, context);
  const loaderModule = route.loaderFile ? formatModuleSpecifier(route.loaderFile, context) : null;

  if (loaderModule) {
    return routeModule
      ? `RouteLoaderData<typeof import(${loaderModule}), typeof import(${routeModule})>`
      : `RouteLoaderData<typeof import(${loaderModule})>`;
  }

  return routeModule ? `RouteLoaderData<typeof import(${routeModule})>` : "unknown";
}

function formatModuleSpecifier(file: string, context: DeclarationContext): string | null {
  if (!IMPORTABLE_MODULE_PATTERN.test(file)) {
    return null;
  }

  // Mirror the runtime's module resolution: root-relative files (pages mode,
  // `/src/...`) resolve from the project root, manifest-relative files
  // (`./routes/...`) resolve from the app manifest's directory.
  const absolutePath = file.startsWith("/")
    ? resolveProjectPath(context.root, file)
    : resolve(context.appDir, file);
  const relativePath = relative(context.declarationDir, absolutePath)
    .replace(/\\/g, "/")
    .replace(IMPORTABLE_MODULE_PATTERN, "");
  const specifier = relativePath.startsWith(".") ? relativePath : `./${relativePath}`;
  return JSON.stringify(specifier);
}

function formatParamsType(params: string[]): string {
  if (params.length === 0) {
    return "Record<never, never>";
  }

  const properties = params.map((param) => `${JSON.stringify(param)}: RouteParamInput;`).join(" ");
  return `{ ${properties} }`;
}
