import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, isAbsolute, relative, resolve } from "node:path";

import { ensureTrailingNewline } from "./utils.js";

const LEGACY_DECLARATION_OUT = "src/pracht-routes.d.ts";

export interface TypegenOutput {
  path: string;
  source: string;
}

interface TypegenOutputPaths {
  capabilitiesOut: string;
  capabilitiesPath: string;
  declarationOut: string;
  declarationPath: string;
  runtimeOut: string;
  runtimePath: string;
}

export function resolveTypegenOutputPath(root: string, outputPath: string): string {
  const absolutePath = isAbsolute(outputPath) ? outputPath : resolve(root, outputPath);
  const relativePath = relative(root, absolutePath);
  if (relativePath === "" || (!relativePath.startsWith("..") && !isAbsolute(relativePath))) {
    return absolutePath;
  }
  throw new Error(`Refusing to write outside the project root: ${outputPath}.`);
}

export function assertDistinctTypegenOutputs(paths: TypegenOutputPaths): void {
  if (outputsCollide(paths.declarationPath, paths.runtimePath)) {
    throw new Error(
      `Declaration output ${paths.declarationOut} shares its basename with ${paths.runtimeOut}. ` +
        "TypeScript drops a .d.ts input that sits next to a same-named .ts file, " +
        "so the generated route types would never apply. Pick a different --out.",
    );
  }
  if (outputsCollide(paths.capabilitiesPath, paths.runtimePath)) {
    throw new Error(
      `Capabilities output ${paths.capabilitiesOut} shares its basename with ${paths.runtimeOut}. ` +
        "TypeScript drops a .d.ts input that sits next to a same-named .ts file, " +
        "so the generated capability types would never apply. Pick a different --capabilities-out.",
    );
  }
  if (
    paths.capabilitiesPath === paths.declarationPath ||
    outputsCollide(paths.declarationPath, paths.capabilitiesPath) ||
    outputsCollide(paths.capabilitiesPath, paths.declarationPath)
  ) {
    throw new Error(
      `Capabilities output ${paths.capabilitiesOut} collides with the declaration output ` +
        `${paths.declarationOut} — identical paths overwrite each other, and TypeScript drops ` +
        "a .d.ts input that sits next to a same-named .ts file. Pick a different --capabilities-out.",
    );
  }
}

export function typegenOutputExists(path: string): boolean {
  return existsSync(path);
}

export function findStaleTypegenOutputs(outputs: TypegenOutput[]): TypegenOutput[] {
  return outputs.filter((output) => !typegenOutputMatches(output.path, output.source));
}

export function writeChangedTypegenOutputs(outputs: TypegenOutput[]): void {
  for (const output of outputs) {
    // Skip identical rewrites so watch-mode regeneration (`pracht dev`)
    // does not trigger spurious HMR updates for the generated modules.
    if (typegenOutputMatches(output.path, output.source)) continue;
    mkdirSync(dirname(output.path), { recursive: true });
    writeFileSync(output.path, output.source, "utf-8");
  }
}

/**
 * Earlier releases wrote the declaration to `src/pracht-routes.d.ts`, where
 * the sibling `pracht-routes.ts` shadowed it. Remove that stale, inert file
 * only when it still carries the generated-file marker.
 */
export function removeLegacyTypegenDeclaration(root: string, declarationPath: string): void {
  const legacyPath = resolve(root, LEGACY_DECLARATION_OUT);
  if (legacyPath === declarationPath || !existsSync(legacyPath)) return;
  if (readFileSync(legacyPath, "utf-8").startsWith("// Generated by `pracht typegen`.")) {
    rmSync(legacyPath);
  }
}

function outputsCollide(declarationPath: string, runtimePath: string): boolean {
  if (declarationPath === runtimePath) return true;

  const declarationStem = declarationPath.replace(/\.d\.(?:ts|mts|cts)$/, "");
  const runtimeStem = runtimePath.replace(/\.(?:ts|tsx|mts|cts)$/, "");
  return declarationStem !== declarationPath && declarationStem === runtimeStem;
}

function typegenOutputMatches(path: string, source: string): boolean {
  return existsSync(path) && readFileSync(path, "utf-8") === ensureTrailingNewline(source);
}
