/** Capability registration and nested-client declaration source generation. */

import { schemaToTypeText } from "@pracht/capabilities";

import type { InspectReport } from "./inspect.js";

type CapabilityEntry = NonNullable<InspectReport["capabilities"]>[number];

/**
 * Register each capability's contract on `Register["capabilities"]`, the
 * capability counterpart of the route declaration file. `invokeCapability()`,
 * `callCapability()`, the generated `capabilities` client, `<Form capability>`,
 * and the capability test host all read this registration once the file is in
 * the program.
 *
 * Beyond input/output types the entry carries the parts of the contract the
 * type layer enforces: `effect` (so a `destructive` call must present a
 * confirmation token) and `exposed` (so only http-exposed capabilities are
 * reachable from the browser).
 *
 * `title`/`description` are emitted as JSDoc on each registration entry and on
 * each explicit nested-client leaf. String arguments to `callCapability()` do
 * not carry that prose, but editor hovers on `capabilities.notes.search` do.
 */
export function buildCapabilityDeclarationSource(capabilities: CapabilityEntry[]): string {
  const lines = [
    "// Generated by `pracht typegen`. Do not edit manually.",
    'import "@pracht/core";',
    'import type { CapabilityClientMethod } from "@pracht/core";',
    "",
    'declare module "@pracht/core" {',
    "  interface Register {",
  ];

  if (capabilities.length === 0) {
    lines.push("    capabilities: Record<never, never>;");
  } else {
    lines.push("    capabilities: {");
    for (const capability of capabilities) {
      // Broken registrations (module failed to load) fall back to `unknown`
      // schemas here; `pracht verify` and `pracht doctor` report the wiring.
      lines.push(...formatCapabilityDoc(capability));
      lines.push(`      ${JSON.stringify(capability.name)}: {`);
      lines.push(`        input: ${schemaToTypeText(capability.input, "input")};`);
      lines.push(`        output: ${schemaToTypeText(capability.output, "output")};`);
      lines.push(`        effect: ${formatCapabilityEffect(capability.effect)};`);
      lines.push(`        exposed: ${formatCapabilityExposure(capability.transports)};`);
      lines.push("      };");
    }
    lines.push("    };");
  }

  lines.push(...formatCapabilityClient(capabilities));
  lines.push("  }");
  lines.push("}");
  lines.push("");
  lines.push("export {};");
  lines.push("");

  return lines.join("\n");
}

interface CapabilityClientTree {
  capability?: CapabilityEntry;
  children: Map<string, CapabilityClientTree>;
}

/**
 * Emit the nested browser client explicitly so JSDoc lives on the properties
 * editors actually expose. A mapped type can reconstruct the shape, but
 * TypeScript does not carry comments from the flat registration through it.
 */
function formatCapabilityClient(capabilities: CapabilityEntry[]): string[] {
  const exposed = capabilities.filter((capability) => capability.transports.includes("http"));
  if (exposed.length === 0) {
    return ["    capabilityClient: Record<never, never>;"];
  }

  const root: CapabilityClientTree = { children: new Map() };
  for (const capability of exposed) {
    let node = root;
    for (const segment of capability.name.split(".")) {
      let child = node.children.get(segment);
      if (!child) {
        child = { children: new Map() };
        node.children.set(segment, child);
      }
      node = child;
    }
    node.capability = capability;
  }

  return ["    capabilityClient: {", ...formatCapabilityClientNode(root, "      "), "    };"];
}

function formatCapabilityClientNode(node: CapabilityClientTree, indent: string): string[] {
  const lines: string[] = [];
  for (const [segment, child] of node.children) {
    if (child.children.size > 0) {
      // Namespace collisions follow the runtime: the namespace wins and the
      // shorter capability remains available through callCapability().
      lines.push(`${indent}${JSON.stringify(segment)}: {`);
      lines.push(...formatCapabilityClientNode(child, `${indent}  `));
      lines.push(`${indent}};`);
      continue;
    }

    if (child.capability) {
      lines.push(...formatCapabilityDoc(child.capability, indent));
      lines.push(
        `${indent}${JSON.stringify(segment)}: CapabilityClientMethod<${JSON.stringify(child.capability.name)}>;`,
      );
    }
  }
  return lines;
}

/**
 * The effect literal drives the type layer's confirmation gate. A registration
 * whose module failed to load has no effect: widen to the full union rather
 * than guessing, so a broken capability never silently loses its gate.
 */
function formatCapabilityEffect(effect: string | null | undefined): string {
  return effect ? JSON.stringify(effect) : '"read" | "write" | "destructive"';
}

/** Exposure literals, so the browser client can drop private capabilities. */
function formatCapabilityExposure(transports: string[] | undefined): string {
  const list = transports ?? [];
  const flag = (name: string) => (list.includes(name) ? "true" : "false");
  return `{ http: ${flag("http")}; webmcp: ${flag("webmcp")}; mcp: ${flag("mcp")} }`;
}

/** `title`/`description` as JSDoc above a registration or client entry. */
function formatCapabilityDoc(capability: CapabilityEntry, indent = "      "): string[] {
  const parts = [capability.title, capability.description].filter(
    (part): part is string => typeof part === "string" && part.trim().length > 0,
  );
  if (parts.length === 0) {
    return [];
  }

  const lines = [`${indent}/**`];
  for (const [index, part] of parts.entries()) {
    if (index > 0) {
      lines.push(`${indent} *`);
    }
    for (const line of part.trim().split(/\r?\n/)) {
      // `*/` inside the contract prose would close the comment early.
      lines.push(`${indent} * ${line.replaceAll("*/", "*\\/")}`.trimEnd());
    }
  }
  lines.push(`${indent} */`);
  return lines;
}
