import { readdir } from "node:fs/promises";
import { resolve } from "node:path";
import type { PrachtAdapter } from "@pracht/vite-plugin";
import type { Plugin } from "vite";

import { createNetlifyServerEntryModule } from "./server-entry.ts";
import type { NetlifyAdapterOptions } from "./types.ts";

const DEFAULT_EXCLUDED_PATHS = ["/assets/*", "/_pracht/*"];

/**
 * Create a Pracht adapter for Netlify Functions v2.
 *
 * The adapter emits `netlify/functions/pracht.mjs`, which re-exports the
 * bundled Pracht server and declares a catch-all path with static asset
 * exclusions. Set Netlify's publish directory to `dist/client`.
 */
export function netlifyAdapter(options: NetlifyAdapterOptions = {}): PrachtAdapter {
  for (const pattern of options.excludedPath ?? []) assertSafeExcludedPath(pattern);
  return {
    id: "netlify",
    serverImports: 'import { resolveApp, resolveApiRoutes } from "@pracht/core/server";',
    createServerEntryModule() {
      return createNetlifyServerEntryModule(options);
    },
    vitePlugins() {
      return [netlifyFunctionPlugin(options)];
    },
  };
}

function netlifyFunctionPlugin(options: NetlifyAdapterOptions): Plugin {
  let root = process.cwd();
  let isSsrBuild = false;

  return {
    name: "pracht:adapter-netlify-function",
    apply: "build",
    configResolved(config) {
      root = config.root;
      isSsrBuild = Boolean(config.build.ssr);
    },
    async closeBundle() {
      if (!isSsrBuild) return;
      await writeNetlifyFunctionWrapper(root, options, false);
    },
  };
}

/** Finalize the generated function after `pracht build` has written every client artifact. */
export async function finalizeNetlifyBuild(
  root: string,
  options: NetlifyAdapterOptions = {},
): Promise<void> {
  for (const pattern of options.excludedPath ?? []) assertSafeExcludedPath(pattern);
  await writeNetlifyFunctionWrapper(root, options, true);
}

async function writeNetlifyFunctionWrapper(
  root: string,
  options: NetlifyAdapterOptions,
  exactIncludedFiles: boolean,
): Promise<void> {
  const { existsSync } = await import("node:fs");
  const { mkdir, writeFile } = await import("node:fs/promises");
  const { join, relative } = await import("node:path");
  const functionName = options.functionName ?? "pracht";
  const functionsDir = options.functionsDir ?? "netlify/functions";
  const excludedPath = [...DEFAULT_EXCLUDED_PATHS, ...(options.excludedPath ?? [])];
  const dir = join(root, functionsDir);
  const wrapper = join(dir, `${functionName}.mjs`);
  const serverDir = join(root, "dist/server");
  const serverEntry = relative(dir, join(serverDir, "server.js")).replaceAll("\\", "/");
  const importPath = serverEntry.startsWith(".") ? serverEntry : `./${serverEntry}`;

  // `excludedPath` URLs bypass the function, so Netlify's static layer
  // serves them without the immutable asset policy and default security
  // headers every other pracht adapter applies to static files. `_headers`
  // in the publish directory is Netlify's mechanism for exactly that. It
  // only affects statically served paths — function responses already
  // carry these headers — so scoping the rules to the excluded prefixes
  // keeps one source of truth per response path.
  const clientDir = join(root, "dist/client");
  const includedClientDir = relative(dir, clientDir).replaceAll("\\", "/");
  const includedServerDir = relative(dir, serverDir).replaceAll("\\", "/");
  await mkdir(clientDir, { recursive: true });
  if (existsSync(join(root, "public/_headers"))) {
    console.warn(
      "public/_headers exists, so @pracht/adapter-netlify will not generate one. " +
        "Make sure it applies `Cache-Control: public, max-age=31536000, immutable` " +
        "to /assets/* and the default security headers to statically served paths.",
    );
  } else {
    await writeFile(join(clientDir, "_headers"), createNetlifyHeadersFile(excludedPath), "utf-8");
  }

  const includedFiles = exactIncludedFiles
    ? await createNetlifyIncludedFiles(
        clientDir,
        includedClientDir,
        includedServerDir,
        excludedPath,
      )
    : createFallbackNetlifyIncludedFiles(includedClientDir, includedServerDir, excludedPath);
  const source = [
    "// Generated by @pracht/adapter-netlify — do not edit.",
    `import handler from ${JSON.stringify(importPath)};`,
    "",
    "export default handler;",
    "",
    `export const config = ${JSON.stringify(
      {
        excludedPath,
        includedFiles,
        name: functionName,
        nodeBundler: "esbuild",
        path: "/*",
      },
      null,
      2,
    )};`,
    "",
  ].join("\n");

  await mkdir(dir, { recursive: true });
  await writeFile(wrapper, source, "utf-8");
}

function createFallbackNetlifyIncludedFiles(
  clientDir: string,
  serverDir: string,
  excludedPath: string[],
): string[] {
  return [
    `${clientDir}/**`,
    ...createNetlifyBundleExclusions(clientDir, excludedPath),
    `${serverDir}/*-manifest.json`,
  ];
}

function createNetlifyBundleExclusions(clientDir: string, excludedPath: string[]): string[] {
  const files: string[] = [];
  for (const pattern of excludedPath) {
    const relativePattern = pattern.slice(1);
    if (relativePattern === "*") files.push(`!${clientDir}/**`);
    else if (relativePattern.endsWith("/*") && !relativePattern.slice(0, -2).includes("*")) {
      files.push(`!${clientDir}/${relativePattern.slice(0, -2)}/**`);
    } else if (!relativePattern.includes("*")) files.push(`!${clientDir}/${relativePattern}`);
  }
  return files;
}

async function createNetlifyIncludedFiles(
  clientDir: string,
  includedClientDir: string,
  includedServerDir: string,
  excludedPath: string[],
): Promise<string[]> {
  const files = await collectNetlifyClientFiles(clientDir, "", excludedPath);
  return [
    ...files.map((file) => `${includedClientDir}/${file}`),
    `${includedServerDir}/*-manifest.json`,
    ...createNetlifyBundleExclusions(includedClientDir, excludedPath),
  ];
}

async function collectNetlifyClientFiles(
  clientDir: string,
  relativeDir: string,
  excludedPath: string[],
): Promise<string[]> {
  const entries = await readdir(resolve(clientDir, relativeDir), { withFileTypes: true });
  const files: string[] = [];

  for (const entry of entries.sort((left, right) => left.name.localeCompare(right.name))) {
    const relativePath = relativeDir ? `${relativeDir}/${entry.name}` : entry.name;
    const pathname = `/${relativePath}`;
    if (isExcludedNetlifyBundlePath(pathname, excludedPath, entry.isDirectory())) continue;
    if (entry.isDirectory()) {
      files.push(...(await collectNetlifyClientFiles(clientDir, relativePath, excludedPath)));
    } else if (entry.isFile()) {
      files.push(relativePath);
    }
  }

  return files;
}

function isExcludedNetlifyBundlePath(
  pathname: string,
  excludedPath: string[],
  directory: boolean,
): boolean {
  return excludedPath.some((pattern) => {
    if (pattern === "/*") return true;
    if (pattern.endsWith("/*") && !pattern.slice(0, -2).includes("*")) {
      const prefix = pattern.slice(0, -2);
      return pathname.startsWith(`${prefix}/`);
    }
    return !directory && !pattern.includes("*") && pathname === pattern;
  });
}

const STATIC_SECURITY_HEADER_LINES = [
  "  Permissions-Policy: accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()",
  "  Referrer-Policy: strict-origin-when-cross-origin",
  "  X-Content-Type-Options: nosniff",
  "  X-Frame-Options: SAMEORIGIN",
];

function createNetlifyHeadersFile(excludedPath: string[]): string {
  const lines = [
    "# Generated by @pracht/adapter-netlify — do not edit.",
    "# These paths bypass the pracht function, so Netlify's static layer needs",
    "# the cache and security headers the function applies everywhere else.",
  ];
  for (const pattern of excludedPath) {
    lines.push(pattern);
    if (pattern === "/assets/*") {
      lines.push("  Cache-Control: public, max-age=31536000, immutable");
    }
    lines.push(...STATIC_SECURITY_HEADER_LINES);
  }
  return `${lines.join("\n")}\n`;
}

/**
 * `excludedPath` values are written into the plain-text `_headers` file, where
 * a value containing whitespace or a newline could inject arbitrary header
 * rules for other paths. They are also URL path patterns, so anything outside
 * printable-ASCII-without-spaces is a mistake anyway — fail the build loudly.
 */
function assertSafeExcludedPath(pattern: string): void {
  if (!pattern.startsWith("/") || !/^[\x21-\x7e]+$/.test(pattern)) {
    throw new Error(
      `netlifyAdapter({ excludedPath }) entries must be URL path patterns starting with "/" ` +
        `and contain no whitespace or control characters; got ${JSON.stringify(pattern)}.`,
    );
  }
}
