import { lstat, readFile, readdir, realpath } from "node:fs/promises";
import { extname, resolve, sep } from "node:path";
import type { PrachtAdapter } from "@pracht/vite-plugin";
import type { Plugin } from "vite";
import {
  applyDefaultSecurityHeaders,
  classifyRevalidationSkip,
  createBaseRedirectResponse,
  createISGRegenerationRequest,
  getTimeRevalidateSeconds,
  handlePrachtRequest,
  isCacheableISGResponse,
  isDangerousPrerenderHeader,
  isMcpResourceMetadataPath,
  jsonResponse,
  matchAppRoute,
  prefersMarkdown,
  preventHeuristicCaching,
  OAUTH_PROTECTED_RESOURCE_WELL_KNOWN,
  PRACHT_REVALIDATE_ENDPOINT,
  readRevalidationRequest,
  RevalidationReport,
  restoreBasePathInRequest,
  resolveRevalidationToken,
  routeSupportsMarkdown,
  stripBase,
  type HandlePrachtRequestOptions,
  type ISGManifestEntry,
  type MarkdownManifest,
  type ModuleRegistry,
  type PrachtApp,
  type ResolvedApiRoute,
  type ResolvedRoute,
} from "@pracht/core/server";

export type HeadersManifest = Record<string, Record<string, string>>;

const GENERATED_NETLIFY_HEADERS_PREAMBLE = "# Generated by @pracht/adapter-netlify — do not edit.";

export interface NetlifyExecutionContext {
  waitUntil?(promise: Promise<unknown>): void;
  [key: string]: unknown;
}

export interface NetlifyContextArgs<
  TNetlifyContext extends NetlifyExecutionContext = NetlifyExecutionContext,
> {
  request: Request;
  context: TNetlifyContext;
}

export interface NetlifyPurgeCacheOptions {
  tags?: string[];
}

export type NetlifyPurgeCache = (options?: NetlifyPurgeCacheOptions) => Promise<unknown>;

/** Purge Netlify's cache without making applications depend on the platform SDK directly. */
export async function purgeNetlifyCache(options?: NetlifyPurgeCacheOptions): Promise<void> {
  const { purgeCache } = await import("@netlify/functions");
  await purgeCache(options);
}

export interface NetlifyCacheOptions {
  /** Seconds stale ISG output may be served while Netlify refreshes it. Set to 0 to disable. Defaults to one year. */
  staleWhileRevalidate?: number;
  /** Edge lifetime for immutable-per-deploy SSG documents. Set to 0 for no freshness. Defaults to one year. */
  staticMaxAge?: number;
}

export interface NetlifyHandlerOptions<
  TNetlifyContext extends NetlifyExecutionContext = NetlifyExecutionContext,
  TContext = TNetlifyContext,
> {
  app: PrachtApp;
  registry?: ModuleRegistry;
  apiRoutes?: ResolvedApiRoute[];
  clientEntryUrl?: string;
  islandsEntryUrl?: string;
  islandsBootstrapRequired?: boolean;
  cssManifest?: Record<string, string[]>;
  jsManifest?: Record<string, string[]>;
  staticDir?: string;
  isgManifest?: Record<string, ISGManifestEntry>;
  headersManifest?: HeadersManifest;
  /** Exact Markdown-capable routes. Omit only for legacy/custom server entries. */
  markdownManifest?: MarkdownManifest;
  createContext?: (args: NetlifyContextArgs<TNetlifyContext>) => TContext | Promise<TContext>;
  purgeCache?: NetlifyPurgeCache;
  cache?: NetlifyCacheOptions;
}

export interface NetlifyAdapterOptions extends NetlifyCacheOptions {
  /** Vite-resolvable module path exporting `createContext(args)`. */
  createContextFrom?: string;
  /** Generated Netlify Function name. Defaults to `pracht`. */
  functionName?: string;
  /** Directory where the generated function wrapper is written. */
  functionsDir?: string;
  /** Additional paths Netlify should serve directly instead of invoking the function. */
  excludedPath?: string[];
}

const DEFAULT_STALE_WHILE_REVALIDATE = 31_536_000;
const DEFAULT_STATIC_MAX_AGE = 31_536_000;
const ROUTE_STATE_REQUEST_HEADER = "x-pracht-route-state-request";
const DEFAULT_EXCLUDED_PATHS = ["/assets/*", "/_pracht/*"];
const ISG_CACHE_TAG = "pracht:isg";
const SHARED_CONTEXT_FIELDS = [
  "account",
  "deploy",
  "json",
  "log",
  "params",
  "server",
  "site",
  "waitUntil",
] as const;
const EMPTY_NETLIFY_GEO = Object.freeze({});
const EMPTY_NETLIFY_COOKIES = Object.freeze({
  delete: rejectSharedContextCookieMutation,
  get: () => undefined,
  set: rejectSharedContextCookieMutation,
});
const NETLIFY_CACHE_POLICY_HEADERS = [
  "cache-control",
  "cdn-cache-control",
  "netlify-cdn-cache-control",
] as const;

/**
 * Create a fetch-style Netlify Functions v2 handler.
 *
 * The generated function claims page URLs so negotiated Markdown and route
 * state requests reach Pracht, while ordinary SSG documents are read from the
 * bundled client output and cached in Netlify's durable cache.
 */
export function createNetlifyHandler<
  TNetlifyContext extends NetlifyExecutionContext = NetlifyExecutionContext,
  TContext = TNetlifyContext,
>(options: NetlifyHandlerOptions<TNetlifyContext, TContext>) {
  const isgManifest = options.isgManifest ?? {};
  const headersManifest = options.headersManifest ?? {};
  const cache = resolveCacheOptions(options.cache);

  return async (request: Request, context: TNetlifyContext): Promise<Response> => {
    const baseRedirect = createBaseRedirectResponse(request);
    if (baseRedirect) return baseRedirect;
    const url = new URL(request.url);
    const routePathname = stripBase(url.pathname);
    const mcpAuth = options.app.agents?.mcp?.auth;
    const isMcpMetadataRequest =
      mcpAuth !== undefined && isMcpResourceMetadataPath(url.pathname, mcpAuth);

    if (routePathname === PRACHT_REVALIDATE_ENDPOINT) {
      return handleNetlifyRevalidation(request, options, isgManifest);
    }

    // Static output and manifests are base-free. A request outside the public
    // base skips every adapter fast path and lets the core runtime return 404.
    const pathname = routePathname === null ? null : normalizePathname(routePathname);
    const routeStateRequest = isRouteStateRequest(request, url);
    const markdownCapable =
      options.markdownManifest === undefined ||
      (pathname !== null && routeSupportsMarkdown(options.markdownManifest, pathname));
    const wantsMarkdown = prefersMarkdown(request.headers.get("accept")) && markdownCapable;
    const staticMethod = request.method === "GET" || request.method === "HEAD";

    // Netlify chooses its CDN cache key before the function runs. Rendering a
    // slashless Request would therefore still leave `/pricing` and
    // `/pricing/` in separate durable entries. Redirect document requests to
    // the manifest's canonical path so only the slashless URL renders.
    if (
      staticMethod &&
      !routeStateRequest &&
      !wantsMarkdown &&
      pathname !== null &&
      pathname !== routePathname &&
      pathname in isgManifest
    ) {
      url.pathname = url.pathname.replace(/\/$/, "");
      const headers = applyDefaultSecurityHeaders(
        new Headers({ location: `${url.pathname}${url.search}` }),
      );
      headers.set("cache-control", "public, max-age=0, must-revalidate");
      return new Response(null, { headers, status: 308 });
    }

    if (
      options.staticDir &&
      staticMethod &&
      !isMcpMetadataRequest &&
      !routeStateRequest &&
      !wantsMarkdown &&
      pathname !== null &&
      !(pathname in isgManifest)
    ) {
      const file = await resolveStaticFile(options.staticDir, pathname);
      if (file) {
        return serveStaticFile(request, file, headersManifest, pathname, cache.staticMaxAge);
      }
    }

    const isgRoute =
      pathname !== null &&
      staticMethod &&
      !isMcpMetadataRequest &&
      !routeStateRequest &&
      !wantsMarkdown &&
      pathname in isgManifest
        ? matchAppRoute(options.app, pathname)?.route
        : undefined;

    // A Netlify CDN response is shared by every visitor. Render ISG documents
    // from a request stripped of cookies, authorization, query, and body so the
    // visitor who triggers a cache miss cannot personalize the stored result.
    const renderRequest =
      isgRoute && pathname !== null
        ? restoreBasePathInRequest(createISGRegenerationRequest(pathname, request))
        : request;
    const renderContext = isgRoute ? createNetlifyISGContext(context, renderRequest) : context;
    const prachtContext = options.createContext
      ? await options.createContext({ request: renderRequest, context: renderContext })
      : (renderContext as unknown as TContext);

    const response = await handlePrachtRequest({
      app: options.app,
      registry: options.registry,
      request: renderRequest,
      context: prachtContext,
      apiRoutes: options.apiRoutes,
      clientEntryUrl: options.clientEntryUrl,
      islandsEntryUrl: options.islandsEntryUrl,
      islandsBootstrapRequired: options.islandsBootstrapRequired,
      cssManifest: options.cssManifest,
      jsManifest: options.jsManifest,
    } satisfies HandlePrachtRequestOptions<TContext>);

    if (isgRoute && pathname !== null) {
      return applyNetlifyISGCacheHeaders(response, isgRoute, pathname, cache);
    }

    const sharesStaticPageCachePolicy =
      options.staticDir !== undefined &&
      staticMethod &&
      wantsMarkdown &&
      pathname !== null &&
      !(pathname in isgManifest) &&
      (await resolveStaticFile(options.staticDir, pathname))?.document === true;

    return applyNetlifyDynamicCacheHeaders(
      request,
      response,
      routeStateRequest,
      sharesStaticPageCachePolicy,
    );
  };
}

/** Cache tag for one concrete ISG pathname. */
export function netlifyRouteCacheTag(pathname: string): string {
  return `pracht:path:${encodeURIComponent(normalizePathname(pathname))}`;
}

/** Return the first candidate containing the Pracht client build directory. */
export async function resolveNetlifyStaticDir(
  candidates: Array<string | null | undefined>,
): Promise<string | undefined> {
  for (const candidate of candidates) {
    if (!candidate) continue;
    const root = resolve(candidate);
    const info = await lstat(root).catch(() => null);
    if (info?.isDirectory()) return root;
  }
  return undefined;
}

export function createNetlifyServerEntryModule(options: NetlifyAdapterOptions = {}): string {
  const contextImport = options.createContextFrom
    ? `import { createContext as createPrachtContext } from ${JSON.stringify(options.createContextFrom)};`
    : "const createPrachtContext = undefined;";

  return [
    'import { existsSync, readFileSync } from "node:fs";',
    'import { dirname, resolve } from "node:path";',
    'import { fileURLToPath } from "node:url";',
    'import { createNetlifyHandler, finalizeNetlifyBuild, purgeNetlifyCache, resolveNetlifyStaticDir } from "@pracht/adapter-netlify";',
    contextImport,
    "",
    "const serverDir = dirname(fileURLToPath(import.meta.url));",
    "function readManifest(name, fallback) {",
    "  for (const file of [",
    '    resolve(process.cwd(), "dist/server", name),',
    "    resolve(serverDir, name),",
    "  ]) {",
    '    if (existsSync(file)) return JSON.parse(readFileSync(file, "utf-8"));',
    "  }",
    "  return fallback;",
    "}",
    "const staticDir = await resolveNetlifyStaticDir([",
    "  process.env.PRACHT_STATIC_DIR,",
    '  resolve(process.cwd(), "dist/client"),',
    '  resolve(serverDir, "../client"),',
    "]);",
    'const isgManifest = readManifest("isg-manifest.json", {});',
    'const headersManifest = readManifest("headers-manifest.json", {});',
    'const markdownManifest = readManifest("markdown-manifest.json", undefined);',
    "",
    "const handler = createNetlifyHandler({",
    "  app: resolvedApp,",
    "  registry,",
    "  apiRoutes,",
    "  clientEntryUrl: clientEntryUrl ?? undefined,",
    "  islandsEntryUrl: islandsEntryUrl ?? undefined,",
    "  islandsBootstrapRequired,",
    "  cssManifest,",
    "  jsManifest,",
    "  staticDir,",
    "  isgManifest,",
    "  headersManifest,",
    "  markdownManifest,",
    "  createContext: createPrachtContext,",
    "  purgeCache: purgeNetlifyCache,",
    `  cache: ${JSON.stringify({
      staleWhileRevalidate: options.staleWhileRevalidate,
      staticMaxAge: options.staticMaxAge,
    })},`,
    "});",
    "",
    "export default function handle(request, context) {",
    "  return handler(request, context);",
    "}",
    `export const finalizePrachtBuild = ({ root }) => finalizeNetlifyBuild(root, ${JSON.stringify(options)}, buildBase);`,
    "",
  ].join("\n");
}

/**
 * Create a Pracht adapter for Netlify Functions v2.
 *
 * The adapter emits `netlify/functions/pracht.mjs`, which re-exports the
 * bundled Pracht server and declares a catch-all path with static asset
 * exclusions. Set Netlify's publish directory to `dist/client`.
 */
export function netlifyAdapter(options: NetlifyAdapterOptions = {}): PrachtAdapter {
  for (const pattern of options.excludedPath ?? []) assertSafeExcludedPath(pattern);
  return {
    id: "netlify",
    serverImports: 'import { resolveApp, resolveApiRoutes } from "@pracht/core/server";',
    createServerEntryModule() {
      return createNetlifyServerEntryModule(options);
    },
    vitePlugins() {
      return [netlifyFunctionPlugin(options)];
    },
  };
}

function netlifyFunctionPlugin(options: NetlifyAdapterOptions): Plugin {
  let root = process.cwd();
  let isSsrBuild = false;
  let base = "/";

  return {
    name: "pracht:adapter-netlify-function",
    apply: "build",
    configResolved(config) {
      root = config.root;
      isSsrBuild = Boolean(config.build.ssr);
      base = config.base || "/";
    },
    async closeBundle() {
      if (!isSsrBuild) return;
      await writeNetlifyFunctionWrapper(root, options, false, base);
    },
  };
}

/** Finalize the generated function after `pracht build` has written every client artifact. */
export async function finalizeNetlifyBuild(
  root: string,
  options: NetlifyAdapterOptions = {},
  base = "/",
): Promise<void> {
  for (const pattern of options.excludedPath ?? []) assertSafeExcludedPath(pattern);
  await writeNetlifyFunctionWrapper(root, options, true, base);
}

async function writeNetlifyFunctionWrapper(
  root: string,
  options: NetlifyAdapterOptions,
  exactIncludedFiles: boolean,
  base: string,
): Promise<void> {
  const { existsSync } = await import("node:fs");
  const { mkdir, writeFile } = await import("node:fs/promises");
  const { join, relative } = await import("node:path");
  const functionName = options.functionName ?? "pracht";
  const functionsDir = options.functionsDir ?? "netlify/functions";
  // Netlify's static publish tree stays base-free. Under a sub-path deploy,
  // `/app/assets/*` cannot bypass the function and map onto `/assets/*`, so
  // keep every client file inside the function bundle and let the runtime
  // strip the public base before serving it. Custom exclusions still apply to
  // their literal origin-root URLs, but must not prune the base-mounted copy.
  const defaultExcludedPaths = hasSubpathDeployBase(base) ? [] : DEFAULT_EXCLUDED_PATHS;
  const excludedPath = [...defaultExcludedPaths, ...(options.excludedPath ?? [])];
  const bundledPathExclusions = hasSubpathDeployBase(base) ? [] : excludedPath;
  const dir = join(root, functionsDir);
  const wrapper = join(dir, `${functionName}.mjs`);
  const serverDir = join(root, "dist/server");
  const serverEntry = relative(dir, join(serverDir, "server.js")).replaceAll("\\", "/");
  const importPath = serverEntry.startsWith(".") ? serverEntry : `./${serverEntry}`;

  // `excludedPath` URLs bypass the function, so Netlify's static layer
  // serves them without the immutable asset policy and default security
  // headers every other pracht adapter applies to static files. `_headers`
  // in the publish directory is Netlify's mechanism for exactly that. It
  // only affects statically served paths — function responses already
  // carry these headers — so scoping the rules to the excluded prefixes
  // keeps one source of truth per response path.
  const clientDir = join(root, "dist/client");
  const includedClientDir = relative(dir, clientDir).replaceAll("\\", "/");
  const includedServerDir = relative(dir, serverDir).replaceAll("\\", "/");
  await mkdir(clientDir, { recursive: true });
  const clientHeadersPath = join(clientDir, "_headers");
  const clientHeadersAreHandAuthored =
    existsSync(clientHeadersPath) &&
    !(await readFile(clientHeadersPath, "utf-8")).startsWith(GENERATED_NETLIFY_HEADERS_PREAMBLE);
  const handAuthoredHeaders = clientHeadersAreHandAuthored
    ? "dist/client/_headers copied from Vite's configured publicDir"
    : undefined;
  if (handAuthoredHeaders) {
    console.warn(
      `${handAuthoredHeaders} exists, so @pracht/adapter-netlify will not generate one. ` +
        "Make sure it applies `Cache-Control: public, max-age=31536000, immutable` " +
        "to /assets/*, preserves generated build headers, and applies the default security " +
        "headers to statically served paths.",
    );
  } else {
    const headersManifestPath = join(serverDir, "headers-manifest.json");
    const headersManifest =
      exactIncludedFiles && existsSync(headersManifestPath)
        ? parseNetlifyHeadersManifest(await readFile(headersManifestPath, "utf-8"))
        : {};
    await writeFile(
      clientHeadersPath,
      createNetlifyHeadersFile(excludedPath, headersManifest),
      "utf-8",
    );
  }

  const includedFiles = exactIncludedFiles
    ? await createNetlifyIncludedFiles(
        clientDir,
        includedClientDir,
        includedServerDir,
        bundledPathExclusions,
      )
    : createFallbackNetlifyIncludedFiles(
        includedClientDir,
        includedServerDir,
        bundledPathExclusions,
      );
  const source = [
    "// Generated by @pracht/adapter-netlify — do not edit.",
    `import handler from ${JSON.stringify(importPath)};`,
    "",
    "export default handler;",
    "",
    `export const config = ${JSON.stringify(
      {
        excludedPath,
        includedFiles,
        name: functionName,
        nodeBundler: "esbuild",
        path: "/*",
      },
      null,
      2,
    )};`,
    "",
  ].join("\n");

  await mkdir(dir, { recursive: true });
  await writeFile(wrapper, source, "utf-8");
}

function hasSubpathDeployBase(base: string): boolean {
  return base !== "/" && base.startsWith("/") && !base.startsWith("//");
}

function createFallbackNetlifyIncludedFiles(
  clientDir: string,
  serverDir: string,
  excludedPath: string[],
): string[] {
  return [
    `${clientDir}/**`,
    ...createNetlifyBundleExclusions(clientDir, excludedPath),
    `${serverDir}/*-manifest.json`,
  ];
}

function createNetlifyBundleExclusions(clientDir: string, excludedPath: string[]): string[] {
  const files: string[] = [];
  for (const pattern of excludedPath) {
    const relativePattern = pattern.slice(1);
    if (relativePattern === "*") files.push(`!${clientDir}/**`);
    else if (relativePattern.endsWith("/*") && !relativePattern.slice(0, -2).includes("*")) {
      files.push(`!${clientDir}/${relativePattern.slice(0, -2)}/**`);
    } else if (!relativePattern.includes("*")) files.push(`!${clientDir}/${relativePattern}`);
  }
  return files;
}

async function createNetlifyIncludedFiles(
  clientDir: string,
  includedClientDir: string,
  includedServerDir: string,
  excludedPath: string[],
): Promise<string[]> {
  const files = await collectNetlifyClientFiles(clientDir, "", excludedPath);
  return [
    ...files.map((file) => `${includedClientDir}/${file}`),
    `${includedServerDir}/*-manifest.json`,
    ...createNetlifyBundleExclusions(includedClientDir, excludedPath),
  ];
}

async function collectNetlifyClientFiles(
  clientDir: string,
  relativeDir: string,
  excludedPath: string[],
): Promise<string[]> {
  const entries = await readdir(resolve(clientDir, relativeDir), { withFileTypes: true });
  const files: string[] = [];

  for (const entry of entries.sort((left, right) => left.name.localeCompare(right.name))) {
    const relativePath = relativeDir ? `${relativeDir}/${entry.name}` : entry.name;
    const pathname = `/${relativePath}`;
    if (isExcludedNetlifyBundlePath(pathname, excludedPath, entry.isDirectory())) continue;
    if (entry.isDirectory()) {
      files.push(...(await collectNetlifyClientFiles(clientDir, relativePath, excludedPath)));
    } else if (entry.isFile()) {
      files.push(relativePath);
    }
  }

  return files;
}

function isExcludedNetlifyBundlePath(
  pathname: string,
  excludedPath: string[],
  directory: boolean,
): boolean {
  return excludedPath.some((pattern) => {
    if (pattern === "/*") return true;
    if (pattern.endsWith("/*") && !pattern.slice(0, -2).includes("*")) {
      const prefix = pattern.slice(0, -2);
      return pathname.startsWith(`${prefix}/`);
    }
    return !directory && !pattern.includes("*") && pathname === pattern;
  });
}

const IMMUTABLE_ASSET_CACHE_CONTROL = "public, max-age=31536000, immutable";
const STATIC_SECURITY_HEADERS: ReadonlyArray<readonly [string, string]> = [
  [
    "Permissions-Policy",
    "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()",
  ],
  ["Referrer-Policy", "strict-origin-when-cross-origin"],
  ["X-Content-Type-Options", "nosniff"],
  ["X-Frame-Options", "SAMEORIGIN"],
];

/** Headers the generated `_headers` rule for `pattern` already applies. */
function staticExclusionHeaders(pattern: string): Array<readonly [string, string]> {
  return [
    ...(pattern === "/assets/*" ? [["Cache-Control", IMMUTABLE_ASSET_CACHE_CONTROL] as const] : []),
    ...STATIC_SECURITY_HEADERS,
  ];
}

/**
 * Whether a `_headers` rule for `pathname` can affect a response at all.
 *
 * The generated function claims `path: "/*"` without `preferStatic`, so Netlify
 * invokes it for every request that `excludedPath` does not carve out —
 * including requests for prerendered pages that exist in the publish
 * directory. Those responses come from the function, which applies the same
 * manifest at runtime, so a `_headers` rule for them is dead weight: on a
 * documentation site it is a rule per page.
 *
 * A pattern this cannot evaluate exactly keeps every rule. Netlify's pattern
 * syntax is richer than the subset understood here, and a redundant rule costs
 * bytes where a missing one costs a statically served artifact its media type.
 */
function servedByNetlifyStaticLayer(pathname: string, excludedPath: string[]): boolean {
  return (
    excludedPath.some((pattern) => !isExactNetlifyExclusion(pattern)) ||
    isExcludedNetlifyBundlePath(pathname, excludedPath, false)
  );
}

/** Whether `isExcludedNetlifyBundlePath` decides this pattern exactly. */
function isExactNetlifyExclusion(pattern: string): boolean {
  if (pattern === "/*") return true;
  if (pattern.endsWith("/*")) return !pattern.slice(0, -2).includes("*");
  return !isNetlifyPathPattern(pattern);
}

function createNetlifyHeadersFile(
  excludedPath: string[],
  headersManifest: HeadersManifest,
): string {
  const lines = [
    GENERATED_NETLIFY_HEADERS_PREAMBLE,
    "# These paths bypass the pracht function, so Netlify's static layer needs",
    "# the build, cache, and security headers the function applies everywhere else.",
  ];
  for (const pattern of excludedPath) {
    lines.push(pattern);
    for (const [name, value] of staticExclusionHeaders(pattern)) lines.push(`  ${name}: ${value}`);
  }
  for (const pathname of Object.keys(headersManifest).sort()) {
    if (!servedByNetlifyStaticLayer(pathname, excludedPath)) continue;
    // Netlify concatenates repeated header names across matching rules rather
    // than letting the more specific one win, so a rule that restates what its
    // pattern already applies turns `nosniff` into `nosniff,nosniff`.
    const inherited = new Map(
      excludedPath
        .filter(
          (pattern) =>
            isExactNetlifyExclusion(pattern) &&
            isExcludedNetlifyBundlePath(pathname, [pattern], false),
        )
        .flatMap((pattern) =>
          staticExclusionHeaders(pattern).map(
            ([name, value]) => [name.toLowerCase(), value] as const,
          ),
        ),
    );
    const entries = Object.entries(headersManifest[pathname])
      .filter(([name, value]) => inherited.get(name.toLowerCase()) !== value)
      .sort(([left], [right]) => left.localeCompare(right));
    if (entries.length === 0) continue;
    lines.push(pathname);
    for (const [name, value] of entries) lines.push(`  ${name}: ${value}`);
  }
  return `${lines.join("\n")}\n`;
}

function parseNetlifyHeadersManifest(source: string): HeadersManifest {
  const parsed: unknown = JSON.parse(source);
  if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) {
    throw new Error("dist/server/headers-manifest.json must contain an object.");
  }

  const manifest: HeadersManifest = {};
  for (const [pathname, rawHeaders] of Object.entries(parsed)) {
    if (
      !pathname.startsWith("/") ||
      hasNetlifyRuleWhitespaceOrControl(pathname) ||
      !rawHeaders ||
      typeof rawHeaders !== "object" ||
      Array.isArray(rawHeaders)
    ) {
      throw new Error(
        `Invalid static header rule for ${JSON.stringify(pathname)} in dist/server/headers-manifest.json.`,
      );
    }

    const headers: Record<string, string> = {};
    for (const [name, value] of Object.entries(rawHeaders)) {
      if (
        !/^[!#$%&'*+\-.^_`|~0-9A-Za-z]+$/.test(name) ||
        typeof value !== "string" ||
        /[\r\n]/.test(value)
      ) {
        throw new Error(
          `Invalid header ${JSON.stringify(name)} for ${JSON.stringify(pathname)} in dist/server/headers-manifest.json.`,
        );
      }
      headers[name] = value;
    }

    // Every prerendered page contributes an entry, most of them header-less.
    // They emit no `_headers` rule, so nothing about the path can matter.
    if (Object.keys(headers).length === 0) continue;

    // `*` and a `:`-leading segment are Netlify pattern syntax, so `_headers`
    // cannot express an exact match for such a path. A `getStaticPaths()` slug
    // may legitimately contain either (`encodeURIComponent` leaves `*` alone),
    // and broadening the rule to other paths is worse than dropping it — warn
    // and skip instead of failing an otherwise valid build.
    if (isNetlifyPathPattern(pathname)) {
      console.warn(
        `@pracht/adapter-netlify skipped the build headers for ${JSON.stringify(pathname)}: ` +
          'Netlify reads "*" and ":placeholder" in `_headers` as path patterns, so the rule ' +
          "would apply to other paths instead of matching this one exactly.",
      );
      continue;
    }

    manifest[pathname] = headers;
  }
  return manifest;
}

function isNetlifyPathPattern(pathname: string): boolean {
  return pathname.includes("*") || pathname.split("/").some((segment) => segment.startsWith(":"));
}

function hasNetlifyRuleWhitespaceOrControl(value: string): boolean {
  return [...value].some((character) => {
    const codePoint = character.codePointAt(0);
    return (
      character.trim() === "" || codePoint === undefined || codePoint < 0x20 || codePoint === 0x7f
    );
  });
}

/**
 * `excludedPath` values are written into the plain-text `_headers` file, where
 * a value containing whitespace or a newline could inject arbitrary header
 * rules for other paths. They are also URL path patterns, so anything outside
 * printable-ASCII-without-spaces is a mistake anyway — fail the build loudly.
 */
function assertSafeExcludedPath(pattern: string): void {
  if (!pattern.startsWith("/") || !/^[\x21-\x7e]+$/.test(pattern)) {
    throw new Error(
      `netlifyAdapter({ excludedPath }) entries must be URL path patterns starting with "/" ` +
        `and contain no whitespace or control characters; got ${JSON.stringify(pattern)}.`,
    );
  }
  if (
    pattern === OAUTH_PROTECTED_RESOURCE_WELL_KNOWN ||
    pattern.startsWith(`${OAUTH_PROTECTED_RESOURCE_WELL_KNOWN}/`) ||
    isExcludedNetlifyBundlePath(OAUTH_PROTECTED_RESOURCE_WELL_KNOWN, [pattern], false)
  ) {
    throw new Error(
      `netlifyAdapter({ excludedPath }) entry ${JSON.stringify(pattern)} would bypass Pracht's OAuth protected-resource metadata handler. Remove this exclusion; the ${OAUTH_PROTECTED_RESOURCE_WELL_KNOWN} namespace is framework-reserved.`,
    );
  }
}

async function handleNetlifyRevalidation<TNetlifyContext extends NetlifyExecutionContext, TContext>(
  request: Request,
  options: NetlifyHandlerOptions<TNetlifyContext, TContext>,
  isgManifest: Record<string, ISGManifestEntry>,
): Promise<Response> {
  const parsed = await readRevalidationRequest(request, resolveRevalidationToken());
  if (!parsed.ok) return parsed.response;

  const report = new RevalidationReport();
  for (const pathname of parsed.paths) {
    const canonicalPathname = normalizePathname(pathname);
    const entry = isgManifest[canonicalPathname];
    const matched = matchAppRoute(options.app, canonicalPathname)?.route ?? null;
    const reason = classifyRevalidationSkip(
      entry ? { ...entry, render: "isg" } : undefined,
      Boolean(entry),
      matched,
    );
    if (reason) {
      report.skipped(pathname, reason);
      continue;
    }
    if (!options.purgeCache) {
      report.failed(pathname, "cache_purge_unavailable");
      continue;
    }

    try {
      await options.purgeCache({ tags: [netlifyRouteCacheTag(canonicalPathname)] });
      report.revalidated(pathname);
    } catch (error) {
      console.error(`ISG webhook revalidation failed for ${pathname}:`, error);
      report.failed(pathname, "cache_purge_failed");
    }
  }

  return jsonResponse(report.toJSON());
}

function applyNetlifyISGCacheHeaders(
  response: Response,
  route: ResolvedRoute,
  pathname: string,
  cache: Required<NetlifyCacheOptions>,
): Response {
  if (response.status !== 200) return response;

  let prepared = stripDangerousSharedCacheHeaders(response, pathname);
  if (!isCacheableISGResponse(prepared)) return prepared;

  const seconds = getTimeRevalidateSeconds(route.revalidate) ?? cache.staticMaxAge;
  const headers = new Headers(prepared.headers);
  if (!hasExplicitCachePolicy(headers)) {
    headers.set(
      "netlify-cdn-cache-control",
      `public, durable, max-age=${seconds}, stale-while-revalidate=${cache.staleWhileRevalidate}`,
    );
    headers.set("cache-control", "public, max-age=0, must-revalidate");
  }
  ensureNetlifyPageVary(headers);
  appendNetlifyCacheTags(headers, [ISG_CACHE_TAG, netlifyRouteCacheTag(pathname)]);
  prepared = cloneResponse(prepared, headers);
  return prepared;
}

function applyNetlifyDynamicCacheHeaders(
  request: Request,
  response: Response,
  routeStateRequest: boolean,
  sharesStaticPageCachePolicy: boolean,
): Response {
  const prepared = preventHeuristicCaching(request, response);
  const cacheControl = prepared.headers.get("cache-control");
  if (
    prepared.headers.has("netlify-cdn-cache-control") ||
    !cacheControl ||
    !/(?:^|,)\s*public\b/i.test(cacheControl)
  ) {
    return prepared;
  }

  // A `public` browser policy alone would make Netlify's CDN store this
  // response, so anything that must not be shared has to say so in the CDN's
  // own header before it leaves the function:
  //
  // - Route-state-shaped requests (`?_data=1` or the transport header) answer
  //   with JSON for first-party fetches but fall back to a full HTML document
  //   when browser provenance is missing. Both shapes share one CDN cache key
  //   modulo `Netlify-Vary` — `query` cannot see who asked — so a cached HTML
  //   answer under `?_data=1` would poison every later client navigation's
  //   JSON fetch for the route's TTL. A cross-site `<a href="/page?_data=1">`
  //   is all it takes to plant one.
  // - A response carrying `Set-Cookie` or `Vary: Cookie`/`Authorization` was
  //   rendered from one visitor's request state. Promoting it durable — or
  //   letting the CDN store it off the browser policy — would replay that
  //   visitor's document (and any cookie) to everyone.
  if (routeStateRequest || !isCacheableISGResponse(prepared)) {
    const headers = new Headers(prepared.headers);
    headers.set("netlify-cdn-cache-control", "private");
    return cloneResponse(prepared, headers);
  }

  const headers = new Headers(prepared.headers);
  headers.set("netlify-cdn-cache-control", `${cacheControl}, durable`);
  // The response is now eligible for Netlify's shared cache. `Netlify-Vary`
  // keeps the custom route-state transport separate, while the framework's
  // standard `Vary: Accept` owns content negotiation. `query` preserves
  // Netlify's default full-query cache key.
  if (!headers.has("netlify-vary")) {
    if (sharesStaticPageCachePolicy) ensureNetlifyPageVary(headers);
    else headers.set("netlify-vary", `query,header=${ROUTE_STATE_REQUEST_HEADER}`);
  }
  return cloneResponse(prepared, headers);
}

function stripDangerousSharedCacheHeaders(response: Response, pathname: string): Response {
  const dangerous = [...response.headers.keys()].filter(isDangerousPrerenderHeader);
  if (dangerous.length === 0) return response;

  const headers = new Headers(response.headers);
  for (const name of dangerous) headers.delete(name);
  console.error(
    `Stripped ${dangerous.map((name) => `"${name}"`).join(", ")} from the ISG response for ` +
      `"${pathname}" before Netlify's shared cache stored it.`,
  );
  return cloneResponse(response, headers);
}

interface StaticFileResult {
  filePath: string;
  contentType: string;
  document: boolean;
}

async function resolveStaticFile(
  staticDir: string,
  pathname: string,
): Promise<StaticFileResult | null> {
  const root = resolve(staticDir);
  const exact = resolveUrlPath(root, pathname);
  if (exact && (await isContainedFile(root, exact))) {
    return {
      contentType: MIME_TYPES[extname(exact)] ?? "application/octet-stream",
      document: exact.endsWith(".html"),
      filePath: exact,
    };
  }

  const index =
    pathname === "/" ? resolve(root, "index.html") : resolveUrlPath(root, pathname, "index.html");
  if (!index || !(await isContainedFile(root, index))) return null;
  return { contentType: "text/html; charset=utf-8", document: true, filePath: index };
}

async function serveStaticFile(
  request: Request,
  file: StaticFileResult,
  headersManifest: HeadersManifest,
  pathname: string,
  staticMaxAge: number,
): Promise<Response> {
  const headers = applyDefaultSecurityHeaders(
    new Headers({
      "content-type": file.contentType,
    }),
  );
  applyHeadersManifest(headers, headersManifest, pathname);
  if (!hasExplicitCachePolicy(headers)) {
    headers.set(
      "cache-control",
      pathname.startsWith("/assets/")
        ? "public, max-age=31536000, immutable"
        : "public, max-age=0, must-revalidate",
    );
    headers.set("netlify-cdn-cache-control", `public, durable, max-age=${staticMaxAge}`);
  }
  if (file.document) ensureNetlifyPageVary(headers);
  const body = request.method === "HEAD" ? null : await readFile(file.filePath);
  return new Response(body, { headers });
}

function hasExplicitCachePolicy(headers: Headers): boolean {
  return NETLIFY_CACHE_POLICY_HEADERS.some((name) => headers.has(name));
}

/**
 * Netlify's CDN combines standard `Vary` with `Netlify-Vary`. A cached page
 * document uses the platform header for Pracht's custom route-state transport
 * and query collapsing, while standard `Vary: Accept` keeps content-negotiated
 * Markdown separate:
 *
 * - `query=_data` — route-state transport via `?_data=1` gets its own cache
 *   key while every unrelated query parameter collapses onto the pathname
 *   entry (sanitized ISG renders never see the query anyway).
 * - `header=x-pracht-route-state-request` — client navigations request route
 *   state with this header on the page URL itself; without it the CDN would
 *   replay cached HTML to a fetch that needs JSON.
 * - `Vary: Accept` (Markdown-capable routes only) — `Accept` is not a supported
 *   `Netlify-Vary` header value, so the standard content-negotiation header
 *   emitted by the framework owns that variant.
 *
 * Route-state and Markdown responses themselves are never durable-cached, so
 * the extra variants stay cache misses that reach the function.
 */
function ensureNetlifyPageVary(headers: Headers): void {
  if (headers.has("netlify-vary")) return;
  headers.set("netlify-vary", `query=_data,header=${ROUTE_STATE_REQUEST_HEADER}`);
}

function appendNetlifyCacheTags(headers: Headers, requiredTags: string[]): void {
  const tags = (headers.get("netlify-cache-tag") ?? "")
    .split(",")
    .map((tag) => tag.trim())
    .filter(Boolean);
  const normalized = new Set(tags.map((tag) => tag.toLowerCase()));
  for (const tag of requiredTags) {
    if (normalized.has(tag.toLowerCase())) continue;
    tags.push(tag);
    normalized.add(tag.toLowerCase());
  }
  headers.set("netlify-cache-tag", tags.join(","));
}

function applyHeadersManifest(
  headers: Headers,
  headersManifest: HeadersManifest,
  pathname: string,
): void {
  const withoutSlash = pathname.replace(/\/$/, "") || "/";
  const withoutIndex = pathname.replace(/\/index\.html$/, "") || "/";
  const values =
    headersManifest[pathname] ?? headersManifest[withoutSlash] ?? headersManifest[withoutIndex];
  if (!values) return;
  for (const [name, value] of Object.entries(values)) headers.set(name, value);
}

function isRouteStateRequest(request: Request, url: URL): boolean {
  return (
    request.headers.get(ROUTE_STATE_REQUEST_HEADER) === "1" || url.searchParams.get("_data") === "1"
  );
}

function resolveCacheOptions(
  options: NetlifyCacheOptions | undefined,
): Required<NetlifyCacheOptions> {
  return {
    staleWhileRevalidate: nonNegativeInteger(
      options?.staleWhileRevalidate,
      DEFAULT_STALE_WHILE_REVALIDATE,
    ),
    staticMaxAge: nonNegativeInteger(options?.staticMaxAge, DEFAULT_STATIC_MAX_AGE),
  };
}

function createNetlifyISGContext<TContext extends NetlifyExecutionContext>(
  context: TContext,
  request: Request,
): TContext {
  const shared: NetlifyExecutionContext = Object.create(null);

  for (const field of SHARED_CONTEXT_FIELDS) {
    const value = context[field];
    if (value === undefined) continue;
    shared[field] = typeof value === "function" ? value.bind(context) : value;
  }

  // Netlify exposes these values outside the Request object. Mask them as
  // deliberately as createISGRegenerationRequest() strips visitor headers and
  // query data, or a context factory could still personalize shared output.
  shared.cookies = EMPTY_NETLIFY_COOKIES;
  shared.geo = EMPTY_NETLIFY_GEO;
  shared.ip = "";
  shared.requestId = "";
  shared.url = new URL(request.url);

  return shared as TContext;
}

function rejectSharedContextCookieMutation(): never {
  throw new Error("Netlify cookies cannot be changed while rendering a shared ISG response.");
}

function nonNegativeInteger(value: number | undefined, fallback: number): number {
  if (typeof value !== "number" || !Number.isFinite(value)) return fallback;
  const integer = Math.floor(value);
  return integer >= 0 ? integer : fallback;
}

function normalizePathname(pathname: string): string {
  if (!pathname.startsWith("/")) pathname = `/${pathname}`;
  return pathname.length > 1 ? pathname.replace(/\/$/, "") : pathname;
}

function cloneResponse(response: Response, headers: Headers): Response {
  return new Response(response.body, {
    headers,
    status: response.status,
    statusText: response.statusText,
  });
}

function resolveUrlPath(root: string, pathname: string, suffix?: string): string | null {
  const decodedPathname = decodeStaticPathname(pathname);
  if (decodedPathname === null) return null;
  const candidate = suffix
    ? resolve(root, `.${decodedPathname}`, suffix)
    : resolve(root, `.${decodedPathname}`);
  return pathIsInside(root, candidate) ? candidate : null;
}

function decodeStaticPathname(pathname: string): string | null {
  const decodedSegments: string[] = [];
  for (const segment of pathname.split("/")) {
    let decoded: string;
    try {
      decoded = decodeURIComponent(segment);
    } catch {
      return null;
    }
    if (decoded === "." || decoded === ".." || decoded.includes("/") || decoded.includes("\\")) {
      return null;
    }
    if (decoded.includes("\0")) return null;
    decodedSegments.push(decoded);
  }
  return decodedSegments.join("/");
}

async function isContainedFile(root: string, candidate: string): Promise<boolean> {
  const info = await lstat(candidate).catch(() => null);
  if (!info?.isFile() || info.isSymbolicLink()) return false;
  const [rootReal, candidateReal] = await Promise.all([
    realpath(root).catch(() => root),
    realpath(candidate).catch(() => null),
  ]);
  return candidateReal !== null && pathIsInside(resolve(rootReal), resolve(candidateReal));
}

function pathIsInside(root: string, candidate: string): boolean {
  return candidate === root || candidate.startsWith(root.endsWith(sep) ? root : `${root}${sep}`);
}

const MIME_TYPES: Record<string, string> = {
  ".atom": "application/atom+xml",
  ".css": "text/css; charset=utf-8",
  ".gif": "image/gif",
  ".html": "text/html; charset=utf-8",
  ".ico": "image/x-icon",
  ".jpeg": "image/jpeg",
  ".jpg": "image/jpeg",
  ".js": "application/javascript; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".markdown": "text/markdown; charset=utf-8",
  ".md": "text/markdown; charset=utf-8",
  ".otf": "font/otf",
  ".png": "image/png",
  ".svg": "image/svg+xml",
  ".ttf": "font/ttf",
  ".txt": "text/plain; charset=utf-8",
  ".webmanifest": "application/manifest+json",
  ".webp": "image/webp",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".xml": "application/xml; charset=utf-8",
};
