// Generated by `pracht typegen`. Do not edit manually.
import { createHref } from "@pracht/core";
import type { HrefRouteDefinition } from "@pracht/core";

export const routes = [
  {
    id: "index",
    path: "/",
  },
  {
    id: "about",
    path: "/about",
  },
  {
    id: "blog-slug",
    path: "/blog/:slug",
  },
] as const satisfies readonly HrefRouteDefinition[];

export const href = createHref(routes);
