import {
  buildPathFromSegments,
  normalizeHrefParams,
  parseRouteSegments,
  serializeSearch,
} from "./route-matching.ts";
import { isApiValidationErrorBody, type ApiValidationIssue } from "./api-validation.ts";
import type {
  ApiFetchArgs,
  ApiFetchBaseOptions,
  ApiMethodsFor,
  ApiOutputFor,
  ApiPath,
  DefaultApiMethod,
  RouteParamInput,
  SearchParamsInput,
} from "./types.ts";

/**
 * Thrown by `apiFetch()` for non-2xx responses. When the server answered with
 * the standardized validation failure produced by `defineApi()` (HTTP
 * 400/422, `{ error: "validation", issues }`), the normalized issues are
 * available on `error.issues`.
 */
export class ApiFetchError extends Error {
  readonly status: number;
  readonly response: Response;
  /** Parsed response body (JSON when the server sent JSON, text otherwise). */
  readonly body: unknown;
  readonly issues?: ApiValidationIssue[];

  constructor(response: Response, body: unknown) {
    super(`API request to ${response.url || "route"} failed with status ${response.status}`);
    this.name = "ApiFetchError";
    this.status = response.status;
    this.response = response;
    this.body = body;
    if (isApiValidationErrorBody(body)) {
      this.issues = body.issues;
    }
  }
}

interface UntypedApiFetchOptions extends ApiFetchBaseOptions {
  method?: string;
  body?: unknown;
  query?: SearchParamsInput;
  params?: Record<string, RouteParamInput>;
}

/**
 * Fetch an API route with end-to-end types. Path templates, allowed methods,
 * request bodies, and response payloads come from `Register["apiRoutes"]`,
 * generated by `pracht typegen` from your `defineApi()` routes:
 *
 * ```ts
 * const item = await apiFetch("/api/items/:id", {
 *   method: "PUT",
 *   params: { id: "42" },
 *   body: { name: "Pracht" }, // type-checked against the route's body schema
 * });
 * // item is the handler's return type
 * ```
 *
 * Without generated types every path is accepted and payloads are `unknown`.
 * Objects passed as `body` are JSON-encoded (with `Content-Type:
 * application/json`); `FormData`, `URLSearchParams`, `Blob`, typed arrays,
 * streams, and strings pass through unchanged. Non-2xx responses throw
 * `ApiFetchError`. JSON responses are parsed; `text/*` responses resolve to
 * the text; anything else resolves to the raw `Response`.
 */
export async function apiFetch<
  TPath extends ApiPath,
  TMethod extends ApiMethodsFor<TPath> = DefaultApiMethod<TPath>,
>(path: TPath, ...args: ApiFetchArgs<TPath, TMethod>): Promise<ApiOutputFor<TPath, TMethod>> {
  const options = (args[0] ?? {}) as UntypedApiFetchOptions;

  const segments = parseRouteSegments(path);
  const isDynamic = segments.some((segment) => segment.type !== "static");
  const pathname = isDynamic
    ? buildPathFromSegments(segments, normalizeHrefParams(segments, options.params ?? {}))
    : path;
  const url = `${options.baseUrl ?? ""}${pathname}${serializeSearch(options.query)}`;

  const headers = new Headers(options.headers);
  let body: BodyInit | undefined;
  if (options.body !== undefined) {
    if (isRawBody(options.body)) {
      body = options.body;
    } else {
      body = JSON.stringify(options.body);
      if (!headers.has("content-type")) {
        headers.set("content-type", "application/json");
      }
    }
  }

  const fetchImpl = options.fetch ?? fetch;
  const response = await fetchImpl(url, {
    method: options.method ?? "GET",
    headers,
    body,
    signal: options.signal,
  });

  if (!response.ok) {
    throw new ApiFetchError(response, await readResponseBody(response));
  }

  return (await readResponseBody(response)) as ApiOutputFor<TPath, TMethod>;
}

function isRawBody(body: unknown): body is BodyInit {
  return (
    typeof body === "string" ||
    body instanceof FormData ||
    body instanceof URLSearchParams ||
    body instanceof Blob ||
    body instanceof ArrayBuffer ||
    ArrayBuffer.isView(body) ||
    (typeof ReadableStream !== "undefined" && body instanceof ReadableStream)
  );
}

async function readResponseBody(response: Response): Promise<unknown> {
  if (response.status === 204 || response.status === 205) {
    return undefined;
  }

  const contentType = response.headers.get("content-type") ?? "";
  if (contentType.includes("json")) {
    return response.json().catch(() => undefined);
  }
  if (contentType.startsWith("text/")) {
    return response.text();
  }
  return response;
}
